// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OIDCConfigInitParameters struct {

	// (Boolean) Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to true when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to true, so a configuration that was deactivated stays deactivated. Set active = true explicitly to reactivate one.
	// Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to `true` when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to `true`, so a configuration that was deactivated stays deactivated. Set `active = true` explicitly to reactivate one.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) The expected audience claim in tokens issued by the external OIDC provider.
	// The expected audience claim in tokens issued by the external OIDC provider.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// readable description of the OIDC configuration.
	// An optional human-readable description of the OIDC configuration.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	// The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	// A human-readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OIDCConfigObservation struct {

	// (Boolean) Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to true when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to true, so a configuration that was deactivated stays deactivated. Set active = true explicitly to reactivate one.
	// Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to `true` when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to `true`, so a configuration that was deactivated stays deactivated. Set `active = true` explicitly to reactivate one.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) The expected audience claim in tokens issued by the external OIDC provider.
	// The expected audience claim in tokens issued by the external OIDC provider.
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// (String) The RFC 3339 timestamp at which the OIDC configuration was created.
	// The RFC 3339 timestamp at which the OIDC configuration was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The RFC 3339 timestamp at which the OIDC configuration was deactivated, or null while it is active.
	// The RFC 3339 timestamp at which the OIDC configuration was deactivated, or null while it is active.
	DeactivatedAt *string `json:"deactivatedAt,omitempty" tf:"deactivated_at,omitempty"`

	// readable description of the OIDC configuration.
	// An optional human-readable description of the OIDC configuration.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// assigned unique identifier for the OIDC configuration.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	// The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	// A human-readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The unique identifier of the CoreWeave organization that owns the OIDC configuration.
	// The unique identifier of the CoreWeave organization that owns the OIDC configuration.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The RFC 3339 timestamp at which the OIDC configuration was last updated.
	// The RFC 3339 timestamp at which the OIDC configuration was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type OIDCConfigParameters struct {

	// (Boolean) Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to true when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to true, so a configuration that was deactivated stays deactivated. Set active = true explicitly to reactivate one.
	// Whether tokens issued by this OIDC provider are accepted for workload identity federation. Defaults to `true` when omitted on creation. Once a value has been applied it is retained: removing the attribute from configuration keeps the last applied value rather than reverting to `true`, so a configuration that was deactivated stays deactivated. Set `active = true` explicitly to reactivate one.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) The expected audience claim in tokens issued by the external OIDC provider.
	// The expected audience claim in tokens issued by the external OIDC provider.
	// +kubebuilder:validation:Optional
	Audience *string `json:"audience,omitempty" tf:"audience,omitempty"`

	// readable description of the OIDC configuration.
	// An optional human-readable description of the OIDC configuration.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	// The issuer URL of the external OIDC provider. HTTPS is required except for loopback development issuers.
	// +kubebuilder:validation:Optional
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	// A human-readable name for the OIDC configuration. Must contain only letters, numbers, hyphens, and underscores.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OIDCConfigSpec defines the desired state of OIDCConfig
type OIDCConfigSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OIDCConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OIDCConfigInitParameters `json:"initProvider,omitempty"`
}

// OIDCConfigStatus defines the observed state of OIDCConfig.
type OIDCConfigStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OIDCConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OIDCConfig is the Schema for the OIDCConfigs API. Creates and manages an external OpenID Connect (OIDC) trust configuration for CoreWeave workload identity federation.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coreweave}
type OIDCConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.audience) || (has(self.initProvider) && has(self.initProvider.audience))",message="spec.forProvider.audience is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.issuerUrl) || (has(self.initProvider) && has(self.initProvider.issuerUrl))",message="spec.forProvider.issuerUrl is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OIDCConfigSpec   `json:"spec"`
	Status OIDCConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OIDCConfigList contains a list of OIDCConfigs
type OIDCConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OIDCConfig `json:"items"`
}

// Repository type metadata.
var (
	OIDCConfig_Kind             = "OIDCConfig"
	OIDCConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OIDCConfig_Kind}.String()
	OIDCConfig_KindAPIVersion   = OIDCConfig_Kind + "." + CRDGroupVersion.String()
	OIDCConfig_GroupVersionKind = CRDGroupVersion.WithKind(OIDCConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&OIDCConfig{}, &OIDCConfigList{})
}
