// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type BucketInventoryInitParameters struct {

	// (Block, Optional) Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service s3:PutObject and s3:AbortMultipartUpload on report objects. Use depends_on to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. s3:PutBucketPolicy itself evaluates organization permissions only. See policy evaluation. (see below for nested schema)
	// Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service `s3:PutObject` and `s3:AbortMultipartUpload` on report objects. Use `depends_on` to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. `s3:PutBucketPolicy` itself evaluates organization permissions only. See [policy evaluation](https://docs.coreweave.com/products/storage/object-storage/auth-access/policies#policy-evaluation).
	Destination *DestinationInitParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// (Boolean) Whether the inventory configuration is enabled. Defaults to true.
	// Whether the inventory configuration is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block, Optional) Limits the inventory report to objects matching a prefix. (see below for nested schema)
	// Limits the inventory report to objects matching a prefix.
	Filter *FilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) Object versions to include: All includes all versions; Current includes only current versions.
	// Object versions to include: `All` includes all versions; `Current` includes only current versions.
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty" tf:"included_object_versions,omitempty"`

	// (Set of String) Additional report fields: Size, LastModifiedDate, LastAccessedDate, StorageClass, ETag, IsMultipartUploaded, EncryptionStatus, ChecksumAlgorithm. Omit to include no additional fields; an empty set is invalid.
	// Additional report fields: `Size`, `LastModifiedDate`, `LastAccessedDate`, `StorageClass`, `ETag`, `IsMultipartUploaded`, `EncryptionStatus`, `ChecksumAlgorithm`. Omit to include no additional fields; an empty set is invalid.
	// +listType=set
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// (Block, Optional) Required. Schedule for generating the inventory report. (see below for nested schema)
	// Required. Schedule for generating the inventory report.
	Schedule *ScheduleInitParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type BucketInventoryObservation struct {

	// (String) Name of source bucket to which the inventory configuration applies
	// Name of source bucket to which the inventory configuration applies
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Block, Optional) Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service s3:PutObject and s3:AbortMultipartUpload on report objects. Use depends_on to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. s3:PutBucketPolicy itself evaluates organization permissions only. See policy evaluation. (see below for nested schema)
	// Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service `s3:PutObject` and `s3:AbortMultipartUpload` on report objects. Use `depends_on` to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. `s3:PutBucketPolicy` itself evaluates organization permissions only. See [policy evaluation](https://docs.coreweave.com/products/storage/object-storage/auth-access/policies#policy-evaluation).
	Destination *DestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`

	// (Boolean) Whether the inventory configuration is enabled. Defaults to true.
	// Whether the inventory configuration is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block, Optional) Limits the inventory report to objects matching a prefix. (see below for nested schema)
	// Limits the inventory report to objects matching a prefix.
	Filter *FilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Object versions to include: All includes all versions; Current includes only current versions.
	// Object versions to include: `All` includes all versions; `Current` includes only current versions.
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty" tf:"included_object_versions,omitempty"`

	// (String) Name of the inventory configuration. Must be unique within the bucket.
	// Name of the inventory configuration. Must be unique within the bucket.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) Additional report fields: Size, LastModifiedDate, LastAccessedDate, StorageClass, ETag, IsMultipartUploaded, EncryptionStatus, ChecksumAlgorithm. Omit to include no additional fields; an empty set is invalid.
	// Additional report fields: `Size`, `LastModifiedDate`, `LastAccessedDate`, `StorageClass`, `ETag`, `IsMultipartUploaded`, `EncryptionStatus`, `ChecksumAlgorithm`. Omit to include no additional fields; an empty set is invalid.
	// +listType=set
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// (Block, Optional) Required. Schedule for generating the inventory report. (see below for nested schema)
	// Required. Schedule for generating the inventory report.
	Schedule *ScheduleObservation `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type BucketInventoryParameters struct {

	// (String) Name of source bucket to which the inventory configuration applies
	// Name of source bucket to which the inventory configuration applies
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/objectstorage/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v2.NamespacedReference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v2.NamespacedSelector `json:"bucketSelector,omitempty" tf:"-"`

	// (Block, Optional) Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service s3:PutObject and s3:AbortMultipartUpload on report objects. Use depends_on to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. s3:PutBucketPolicy itself evaluates organization permissions only. See policy evaluation. (see below for nested schema)
	// Required. Where the inventory report is written. May be the same bucket as the source. The destination policy must grant the inventory service `s3:PutObject` and `s3:AbortMultipartUpload` on report objects. Use `depends_on` to apply that policy before the inventory configuration. Bucket policies are evaluated after organization policies; requests without a matching bucket grant are implicitly denied even if an organization policy allows them. The policy resource replaces the entire existing bucket policy, so retain all required statements. `s3:PutBucketPolicy` itself evaluates organization permissions only. See [policy evaluation](https://docs.coreweave.com/products/storage/object-storage/auth-access/policies#policy-evaluation).
	// +kubebuilder:validation:Optional
	Destination *DestinationParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// (Boolean) Whether the inventory configuration is enabled. Defaults to true.
	// Whether the inventory configuration is enabled. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Block, Optional) Limits the inventory report to objects matching a prefix. (see below for nested schema)
	// Limits the inventory report to objects matching a prefix.
	// +kubebuilder:validation:Optional
	Filter *FilterParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// (String) Object versions to include: All includes all versions; Current includes only current versions.
	// Object versions to include: `All` includes all versions; `Current` includes only current versions.
	// +kubebuilder:validation:Optional
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty" tf:"included_object_versions,omitempty"`

	// (String) Name of the inventory configuration. Must be unique within the bucket.
	// Name of the inventory configuration. Must be unique within the bucket.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// (Set of String) Additional report fields: Size, LastModifiedDate, LastAccessedDate, StorageClass, ETag, IsMultipartUploaded, EncryptionStatus, ChecksumAlgorithm. Omit to include no additional fields; an empty set is invalid.
	// Additional report fields: `Size`, `LastModifiedDate`, `LastAccessedDate`, `StorageClass`, `ETag`, `IsMultipartUploaded`, `EncryptionStatus`, `ChecksumAlgorithm`. Omit to include no additional fields; an empty set is invalid.
	// +kubebuilder:validation:Optional
	// +listType=set
	OptionalFields []*string `json:"optionalFields,omitempty" tf:"optional_fields,omitempty"`

	// (Block, Optional) Required. Schedule for generating the inventory report. (see below for nested schema)
	// Required. Schedule for generating the inventory report.
	// +kubebuilder:validation:Optional
	Schedule *ScheduleParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type DestinationBucketInitParameters struct {

	// (String) Account ID of the destination bucket owner.
	// Account ID of the destination bucket owner.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) ARN of the destination bucket.
	// ARN of the destination bucket.
	BucketArn *string `json:"bucketArn,omitempty" tf:"bucket_arn,omitempty"`

	// (String) Output format: CSV, TSV, JSON, ORC, or Parquet.
	// Output format: `CSV`, `TSV`, `JSON`, `ORC`, or `Parquet`.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Prefix prepended to the report output path.
	// Prefix prepended to the report output path.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type DestinationBucketObservation struct {

	// (String) Account ID of the destination bucket owner.
	// Account ID of the destination bucket owner.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) ARN of the destination bucket.
	// ARN of the destination bucket.
	BucketArn *string `json:"bucketArn,omitempty" tf:"bucket_arn,omitempty"`

	// (String) Output format: CSV, TSV, JSON, ORC, or Parquet.
	// Output format: `CSV`, `TSV`, `JSON`, `ORC`, or `Parquet`.
	Format *string `json:"format,omitempty" tf:"format,omitempty"`

	// (String) Prefix prepended to the report output path.
	// Prefix prepended to the report output path.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type DestinationBucketParameters struct {

	// (String) Account ID of the destination bucket owner.
	// Account ID of the destination bucket owner.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) ARN of the destination bucket.
	// ARN of the destination bucket.
	// +kubebuilder:validation:Optional
	BucketArn *string `json:"bucketArn" tf:"bucket_arn,omitempty"`

	// (String) Output format: CSV, TSV, JSON, ORC, or Parquet.
	// Output format: `CSV`, `TSV`, `JSON`, `ORC`, or `Parquet`.
	// +kubebuilder:validation:Optional
	Format *string `json:"format" tf:"format,omitempty"`

	// (String) Prefix prepended to the report output path.
	// Prefix prepended to the report output path.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type DestinationInitParameters struct {
}

type DestinationObservation struct {

	// (String) Name of source bucket to which the inventory configuration applies
	// Required. Destination bucket for the report (may equal the source bucket).
	Bucket *DestinationBucketObservation `json:"bucket,omitempty" tf:"bucket,omitempty"`
}

type DestinationParameters struct {

	// (String) Name of source bucket to which the inventory configuration applies
	// Required. Destination bucket for the report (may equal the source bucket).
	// +kubebuilder:validation:Optional
	Bucket *DestinationBucketParameters `json:"bucket,omitempty" tf:"bucket,omitempty"`
}

type FilterInitParameters struct {

	// (String) Prefix prepended to the report output path.
	// Source-object prefix to filter on.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type FilterObservation struct {

	// (String) Prefix prepended to the report output path.
	// Source-object prefix to filter on.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type FilterParameters struct {

	// (String) Prefix prepended to the report output path.
	// Source-object prefix to filter on.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type ScheduleInitParameters struct {

	// (String) How frequently the report is generated: Daily or Weekly.
	// How frequently the report is generated: `Daily` or `Weekly`.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`
}

type ScheduleObservation struct {

	// (String) How frequently the report is generated: Daily or Weekly.
	// How frequently the report is generated: `Daily` or `Weekly`.
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`
}

type ScheduleParameters struct {

	// (String) How frequently the report is generated: Daily or Weekly.
	// How frequently the report is generated: `Daily` or `Weekly`.
	// +kubebuilder:validation:Optional
	Frequency *string `json:"frequency" tf:"frequency,omitempty"`
}

// BucketInventorySpec defines the desired state of BucketInventory
type BucketInventorySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BucketInventoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BucketInventoryInitParameters `json:"initProvider,omitempty"`
}

// BucketInventoryStatus defines the observed state of BucketInventory.
type BucketInventoryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               BucketInventoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BucketInventory is the Schema for the BucketInventorys API. Manages a CoreWeave AI Object Storage bucket inventory configuration. The provider obtains temporary S3 credentials using its configured authentication; no separately managed access-key resource is required. The authenticated identity must have permission to manage inventory configurations on the source bucket and policies on the destination bucket. Learn more about inventory reporting https://docs.coreweave.com/products/storage/object-storage/buckets/inventory-reporting/configure.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coreweave}
type BucketInventory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.includedObjectVersions) || (has(self.initProvider) && has(self.initProvider.includedObjectVersions))",message="spec.forProvider.includedObjectVersions is a required parameter"
	Spec   BucketInventorySpec   `json:"spec"`
	Status BucketInventoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BucketInventoryList contains a list of BucketInventorys
type BucketInventoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BucketInventory `json:"items"`
}

// Repository type metadata.
var (
	BucketInventory_Kind             = "BucketInventory"
	BucketInventory_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BucketInventory_Kind}.String()
	BucketInventory_KindAPIVersion   = BucketInventory_Kind + "." + CRDGroupVersion.String()
	BucketInventory_GroupVersionKind = CRDGroupVersion.WithKind(BucketInventory_Kind)
)

func init() {
	SchemeBuilder.Register(&BucketInventory{}, &BucketInventoryList{})
}
