// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationAccessPolicyInitParameters struct {

	// (Attributes Set) The list of access policy statements associated with this policy. At least one statement is required. (see below for nested schema)
	Statements []StatementsInitParameters `json:"statements,omitempty" tf:"statements,omitempty"`
}

type OrganizationAccessPolicyObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes Set) The list of access policy statements associated with this policy. At least one statement is required. (see below for nested schema)
	Statements []StatementsObservation `json:"statements,omitempty" tf:"statements,omitempty"`
}

type OrganizationAccessPolicyParameters struct {

	// (Attributes Set) The list of access policy statements associated with this policy. At least one statement is required. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Statements []StatementsParameters `json:"statements,omitempty" tf:"statements,omitempty"`
}

type StatementsInitParameters struct {

	// S3 (s3:) and AI Object Storage API (cwobject:). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	// Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the AI Object Storage documentation for guidelines on defining principals.
	// Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining principals.
	// +listType=set
	Principals []*string `json:"principals,omitempty" tf:"principals,omitempty"`

	// (Set of String) Defines which resources the policy applies to. See the AI Object Storage documentation for guidelines on defining resources.
	// Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining resources.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type StatementsObservation struct {

	// S3 (s3:) and AI Object Storage API (cwobject:). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	// Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// (String) The name of the organization access policy, must be unique.
	// A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the AI Object Storage documentation for guidelines on defining principals.
	// Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining principals.
	// +listType=set
	Principals []*string `json:"principals,omitempty" tf:"principals,omitempty"`

	// (Set of String) Defines which resources the policy applies to. See the AI Object Storage documentation for guidelines on defining resources.
	// Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining resources.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type StatementsParameters struct {

	// S3 (s3:) and AI Object Storage API (cwobject:). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	// Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// (String) The name of the organization access policy, must be unique.
	// A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the AI Object Storage documentation for guidelines on defining principals.
	// Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining principals.
	// +kubebuilder:validation:Optional
	// +listType=set
	Principals []*string `json:"principals" tf:"principals,omitempty"`

	// (Set of String) Defines which resources the policy applies to. See the AI Object Storage documentation for guidelines on defining resources.
	// Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about) for guidelines on defining resources.
	// +kubebuilder:validation:Optional
	// +listType=set
	Resources []*string `json:"resources" tf:"resources,omitempty"`
}

// OrganizationAccessPolicySpec defines the desired state of OrganizationAccessPolicy
type OrganizationAccessPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationAccessPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationAccessPolicyInitParameters `json:"initProvider,omitempty"`
}

// OrganizationAccessPolicyStatus defines the observed state of OrganizationAccessPolicy.
type OrganizationAccessPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationAccessPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationAccessPolicy is the Schema for the OrganizationAccessPolicys API. Organization access policies https://docs.coreweave.com/products/storage/object-storage/auth-access/organization-policies/about enforce permissions for AI Object Storage across your entire CoreWeave organization, automatically covering every resource, bucket, and user in your account. At least one organization access policy must be in place before you can create a bucket.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coreweave}
type OrganizationAccessPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.statements) || (has(self.initProvider) && has(self.initProvider.statements))",message="spec.forProvider.statements is a required parameter"
	Spec   OrganizationAccessPolicySpec   `json:"spec"`
	Status OrganizationAccessPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationAccessPolicyList contains a list of OrganizationAccessPolicys
type OrganizationAccessPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationAccessPolicy `json:"items"`
}

// Repository type metadata.
var (
	OrganizationAccessPolicy_Kind             = "OrganizationAccessPolicy"
	OrganizationAccessPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationAccessPolicy_Kind}.String()
	OrganizationAccessPolicy_KindAPIVersion   = OrganizationAccessPolicy_Kind + "." + CRDGroupVersion.String()
	OrganizationAccessPolicy_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationAccessPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationAccessPolicy{}, &OrganizationAccessPolicyList{})
}
