// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AutoscalingInitParameters struct {

	// (List of String) Ordered preference list of capacity classes to use. Order is significant: the first satisfiable class wins. Allowed values: CAPACITY_CLASS_RESERVED, CAPACITY_CLASS_ON_DEMAND.
	// Ordered preference list of [capacity classes](https://docs.coreweave.com/products/inference/scaling#capacity-claims) to use. Order is significant: the first satisfiable class wins. Allowed values: `CAPACITY_CLASS_RESERVED`, `CAPACITY_CLASS_ON_DEMAND`.
	CapacityClasses []*string `json:"capacityClasses,omitempty" tf:"capacity_classes,omitempty"`

	// (Number) Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	// Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// (Number) Maximum number of instances. Must be ≥1.
	// Maximum number of instances. Must be ≥1.
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// (Number) Minimum number of instances. Must be ≥1.
	// Minimum number of instances. Must be ≥1.
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// deployment scaling (0-1000). Higher values win when there is contention.
	// Priority for cross-deployment scaling (0-1000). Higher values win when there is contention.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type AutoscalingObservation struct {

	// (List of String) Ordered preference list of capacity classes to use. Order is significant: the first satisfiable class wins. Allowed values: CAPACITY_CLASS_RESERVED, CAPACITY_CLASS_ON_DEMAND.
	// Ordered preference list of [capacity classes](https://docs.coreweave.com/products/inference/scaling#capacity-claims) to use. Order is significant: the first satisfiable class wins. Allowed values: `CAPACITY_CLASS_RESERVED`, `CAPACITY_CLASS_ON_DEMAND`.
	CapacityClasses []*string `json:"capacityClasses,omitempty" tf:"capacity_classes,omitempty"`

	// (Number) Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	// Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// (Number) Maximum number of instances. Must be ≥1.
	// Maximum number of instances. Must be ≥1.
	Max *float64 `json:"max,omitempty" tf:"max,omitempty"`

	// (Number) Minimum number of instances. Must be ≥1.
	// Minimum number of instances. Must be ≥1.
	Min *float64 `json:"min,omitempty" tf:"min,omitempty"`

	// deployment scaling (0-1000). Higher values win when there is contention.
	// Priority for cross-deployment scaling (0-1000). Higher values win when there is contention.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type AutoscalingParameters struct {

	// (List of String) Ordered preference list of capacity classes to use. Order is significant: the first satisfiable class wins. Allowed values: CAPACITY_CLASS_RESERVED, CAPACITY_CLASS_ON_DEMAND.
	// Ordered preference list of [capacity classes](https://docs.coreweave.com/products/inference/scaling#capacity-claims) to use. Order is significant: the first satisfiable class wins. Allowed values: `CAPACITY_CLASS_RESERVED`, `CAPACITY_CLASS_ON_DEMAND`.
	// +kubebuilder:validation:Optional
	CapacityClasses []*string `json:"capacityClasses,omitempty" tf:"capacity_classes,omitempty"`

	// (Number) Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	// Concurrency per instance target (≥1). Controls latency vs throughput tradeoffs.
	// +kubebuilder:validation:Optional
	Concurrency *float64 `json:"concurrency,omitempty" tf:"concurrency,omitempty"`

	// (Number) Maximum number of instances. Must be ≥1.
	// Maximum number of instances. Must be ≥1.
	// +kubebuilder:validation:Optional
	Max *float64 `json:"max" tf:"max,omitempty"`

	// (Number) Minimum number of instances. Must be ≥1.
	// Minimum number of instances. Must be ≥1.
	// +kubebuilder:validation:Optional
	Min *float64 `json:"min" tf:"min,omitempty"`

	// deployment scaling (0-1000). Higher values win when there is contention.
	// Priority for cross-deployment scaling (0-1000). Higher values win when there is contention.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type DeploymentConditionsInitParameters struct {
}

type DeploymentConditionsObservation struct {

	// (String) RFC3339 timestamp of the last condition transition.
	// RFC3339 timestamp of the last condition transition.
	LastUpdateTime *string `json:"lastUpdateTime,omitempty" tf:"last_update_time,omitempty"`

	// readable message about the condition's last transition.
	// A human-readable message about the condition's last transition.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// readable reason for the condition's last transition.
	// A short, machine-readable reason for the condition's last transition.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// (String) The current status of the deployment. See the Inference API overview for status values. Apply returns once resources are applied rather than once serving, so this may not be ready immediately after apply; poll the API for live readiness.
	// The condition status (`True`, `False`, or `Unknown`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The condition type (e.g. Ready, Progressing).
	// The condition type (e.g. `Ready`, `Progressing`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeploymentConditionsParameters struct {
}

type DeploymentInitParameters struct {

	// (Attributes) Autoscaling configuration. (see below for nested schema)
	Autoscaling *AutoscalingInitParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Boolean) Whether the deployment is disabled.
	// Whether the deployment is disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) The gateway IDs to associate the deployment with. At least one is required.
	// The [gateway](https://docs.coreweave.com/products/inference/gateways) IDs to associate the deployment with. At least one is required.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/inference/v1alpha1.Gateway
	// +listType=set
	GatewayIds []*string `json:"gatewayIds,omitempty" tf:"gateway_ids,omitempty"`

	// References to Gateway in inference to populate gatewayIds.
	// +kubebuilder:validation:Optional
	GatewayIdsRefs []v2.NamespacedReference `json:"gatewayIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Gateway in inference to populate gatewayIds.
	// +kubebuilder:validation:Optional
	GatewayIdsSelector *v2.NamespacedSelector `json:"gatewayIdsSelector,omitempty" tf:"-"`

	// (Attributes) Model configuration. (see below for nested schema)
	Model *ModelInitParameters `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The name of the deployment. Must be a valid hostname label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) GPU resource configuration for the deployment. (see below for nested schema)
	Resources *DeploymentResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Attributes) Runtime selection and configuration. (see below for nested schema)
	Runtime *RuntimeInitParameters `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// (Attributes) Traffic configuration. Omit to accept the API default (weight 0, which normalizes to 100% when no other deployment shares the model name). After apply, weight is populated from the API. (see below for nested schema)
	Traffic *TrafficInitParameters `json:"traffic,omitempty" tf:"traffic,omitempty"`
}

type DeploymentObservation struct {

	// (Attributes) Autoscaling configuration. (see below for nested schema)
	Autoscaling *AutoscalingObservation `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Attributes List) Detailed status conditions for the deployment. (see below for nested schema)
	Conditions []DeploymentConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (String) RFC3339 timestamp of when the deployment was created.
	// RFC3339 timestamp of when the deployment was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether the deployment is disabled.
	// Whether the deployment is disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) The gateway IDs to associate the deployment with. At least one is required.
	// The [gateway](https://docs.coreweave.com/products/inference/gateways) IDs to associate the deployment with. At least one is required.
	// +listType=set
	GatewayIds []*string `json:"gatewayIds,omitempty" tf:"gateway_ids,omitempty"`

	// (String) The unique identifier of the deployment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Model configuration. (see below for nested schema)
	Model *ModelObservation `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The name of the deployment. Must be a valid hostname label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that owns the deployment.
	// The organization ID that owns the deployment.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Attributes) GPU resource configuration for the deployment. (see below for nested schema)
	Resources *DeploymentResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Attributes) Runtime selection and configuration. (see below for nested schema)
	Runtime *RuntimeObservation `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// (String) The current status of the deployment. See the Inference API overview for status values. Apply returns once resources are applied rather than once serving, so this may not be ready immediately after apply; poll the API for live readiness.
	// The current status of the deployment. See the [Inference API overview](https://docs.coreweave.com/products/inference/reference/api-overview) for status values. Apply returns once resources are applied rather than once serving, so this may not be ready immediately after apply; poll the API for live readiness.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Attributes) Traffic configuration. Omit to accept the API default (weight 0, which normalizes to 100% when no other deployment shares the model name). After apply, weight is populated from the API. (see below for nested schema)
	Traffic *TrafficObservation `json:"traffic,omitempty" tf:"traffic,omitempty"`

	// (String) RFC3339 timestamp of when the deployment was last updated.
	// RFC3339 timestamp of when the deployment was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type DeploymentParameters struct {

	// (Attributes) Autoscaling configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Autoscaling *AutoscalingParameters `json:"autoscaling,omitempty" tf:"autoscaling,omitempty"`

	// (Boolean) Whether the deployment is disabled.
	// Whether the deployment is disabled.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// (Set of String) The gateway IDs to associate the deployment with. At least one is required.
	// The [gateway](https://docs.coreweave.com/products/inference/gateways) IDs to associate the deployment with. At least one is required.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/inference/v1alpha1.Gateway
	// +kubebuilder:validation:Optional
	// +listType=set
	GatewayIds []*string `json:"gatewayIds,omitempty" tf:"gateway_ids,omitempty"`

	// References to Gateway in inference to populate gatewayIds.
	// +kubebuilder:validation:Optional
	GatewayIdsRefs []v2.NamespacedReference `json:"gatewayIdsRefs,omitempty" tf:"-"`

	// Selector for a list of Gateway in inference to populate gatewayIds.
	// +kubebuilder:validation:Optional
	GatewayIdsSelector *v2.NamespacedSelector `json:"gatewayIdsSelector,omitempty" tf:"-"`

	// (Attributes) Model configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Model *ModelParameters `json:"model,omitempty" tf:"model,omitempty"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The name of the deployment. Must be a valid hostname label.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) GPU resource configuration for the deployment. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Resources *DeploymentResourcesParameters `json:"resources,omitempty" tf:"resources,omitempty"`

	// (Attributes) Runtime selection and configuration. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Runtime *RuntimeParameters `json:"runtime,omitempty" tf:"runtime,omitempty"`

	// (Attributes) Traffic configuration. Omit to accept the API default (weight 0, which normalizes to 100% when no other deployment shares the model name). After apply, weight is populated from the API. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Traffic *TrafficParameters `json:"traffic,omitempty" tf:"traffic,omitempty"`
}

type DeploymentResourcesInitParameters struct {

	// (Number) Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	// Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	GpuCount *float64 `json:"gpuCount,omitempty" tf:"gpu_count,omitempty"`

	// (String) The instance type to use.
	// The instance type to use.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`
}

type DeploymentResourcesObservation struct {

	// (Number) Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	// Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	GpuCount *float64 `json:"gpuCount,omitempty" tf:"gpu_count,omitempty"`

	// (String) The instance type to use.
	// The instance type to use.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`
}

type DeploymentResourcesParameters struct {

	// (Number) Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	// Number of GPUs per instance. Must be one of: 1, 2, 4, 8, 16.
	// +kubebuilder:validation:Optional
	GpuCount *float64 `json:"gpuCount" tf:"gpu_count,omitempty"`

	// (String) The instance type to use.
	// The instance type to use.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`
}

type ModelInitParameters struct {

	// (String) The CAIOS bucket the model is stored in. The inference service account must have bucket access.
	// The CAIOS bucket the model is stored in. The inference service account must have [bucket access](https://docs.coreweave.com/products/inference/models#grant-inference-access-to-your-bucket).
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/objectstorage/v1alpha1.Bucket
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v2.NamespacedReference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v2.NamespacedSelector `json:"bucketSelector,omitempty" tf:"-"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The model name used in API requests (e.g. the `/models` endpoint). Length must be 4-63 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The CAIOS path to the model and its configuration files.
	// The CAIOS path to the model and its configuration files.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type ModelObservation struct {

	// (String) The CAIOS bucket the model is stored in. The inference service account must have bucket access.
	// The CAIOS bucket the model is stored in. The inference service account must have [bucket access](https://docs.coreweave.com/products/inference/models#grant-inference-access-to-your-bucket).
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The model name used in API requests (e.g. the `/models` endpoint). Length must be 4-63 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The CAIOS path to the model and its configuration files.
	// The CAIOS path to the model and its configuration files.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`
}

type ModelParameters struct {

	// (String) The CAIOS bucket the model is stored in. The inference service account must have bucket access.
	// The CAIOS bucket the model is stored in. The inference service account must have [bucket access](https://docs.coreweave.com/products/inference/models#grant-inference-access-to-your-bucket).
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/objectstorage/v1alpha1.Bucket
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// Reference to a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketRef *v2.NamespacedReference `json:"bucketRef,omitempty" tf:"-"`

	// Selector for a Bucket in objectstorage to populate bucket.
	// +kubebuilder:validation:Optional
	BucketSelector *v2.NamespacedSelector `json:"bucketSelector,omitempty" tf:"-"`

	// (String) The name of the deployment. Must be a valid hostname label.
	// The model name used in API requests (e.g. the `/models` endpoint). Length must be 4-63 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The CAIOS path to the model and its configuration files.
	// The CAIOS path to the model and its configuration files.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`
}

type RuntimeInitParameters struct {

	// (String) The inference engine to use.
	// The inference engine to use.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// specific configuration key/value pairs.
	// Engine-specific configuration key/value pairs.
	// +mapType=granular
	EngineConfig map[string]*string `json:"engineConfig,omitempty" tf:"engine_config,omitempty"`

	// specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names; unsupported names are rejected by the API.
	// Engine-specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by `data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names`; unsupported names are rejected by the API.
	// +mapType=granular
	EngineEnv map[string]*string `json:"engineEnv,omitempty" tf:"engine_env,omitempty"`

	// (String) The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. 1.2.3).
	// The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. `1.2.3`).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type RuntimeObservation struct {

	// (String) The inference engine to use.
	// The inference engine to use.
	Engine *string `json:"engine,omitempty" tf:"engine,omitempty"`

	// specific configuration key/value pairs.
	// Engine-specific configuration key/value pairs.
	// +mapType=granular
	EngineConfig map[string]*string `json:"engineConfig,omitempty" tf:"engine_config,omitempty"`

	// specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names; unsupported names are rejected by the API.
	// Engine-specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by `data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names`; unsupported names are rejected by the API.
	// +mapType=granular
	EngineEnv map[string]*string `json:"engineEnv,omitempty" tf:"engine_env,omitempty"`

	// (String) The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. 1.2.3).
	// The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. `1.2.3`).
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type RuntimeParameters struct {

	// (String) The inference engine to use.
	// The inference engine to use.
	// +kubebuilder:validation:Optional
	Engine *string `json:"engine" tf:"engine,omitempty"`

	// specific configuration key/value pairs.
	// Engine-specific configuration key/value pairs.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	EngineConfig map[string]*string `json:"engineConfig,omitempty" tf:"engine_config,omitempty"`

	// specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names; unsupported names are rejected by the API.
	// Engine-specific environment variables to inject into the model runtime container. Variable names must come from the selected engine's server-side allow list, exposed by `data.coreweave_inference_deployment_parameters.<name>.engine_env_options[<engine>].allowed_names`; unsupported names are rejected by the API.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	EngineEnv map[string]*string `json:"engineEnv,omitempty" tf:"engine_env,omitempty"`

	// (String) The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. 1.2.3).
	// The version of the engine. If not set, defaults to the latest available version. Must follow semver format (e.g. `1.2.3`).
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type TrafficInitParameters struct {

	// 1000). Values are normalized into percentages across deployments with the same model name.
	// Traffic weight (0-1000). Values are normalized into percentages across deployments with the same model name.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type TrafficObservation struct {

	// 1000). Values are normalized into percentages across deployments with the same model name.
	// Traffic weight (0-1000). Values are normalized into percentages across deployments with the same model name.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type TrafficParameters struct {

	// 1000). Values are normalized into percentages across deployments with the same model name.
	// Traffic weight (0-1000). Values are normalized into percentages across deployments with the same model name.
	// +kubebuilder:validation:Optional
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

// DeploymentSpec defines the desired state of Deployment
type DeploymentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DeploymentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeploymentInitParameters `json:"initProvider,omitempty"`
}

// DeploymentStatus defines the observed state of Deployment.
type DeploymentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DeploymentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Deployment is the Schema for the Deployments API. Create and manage CoreWeave Managed Inference https://docs.coreweave.com/products/inference deployments. See the getting started walkthrough https://docs.coreweave.com/products/inference/getting-started for the gateway-to-deployment flow.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coreweave}
type Deployment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.autoscaling) || (has(self.initProvider) && has(self.initProvider.autoscaling))",message="spec.forProvider.autoscaling is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.model) || (has(self.initProvider) && has(self.initProvider.model))",message="spec.forProvider.model is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resources) || (has(self.initProvider) && has(self.initProvider.resources))",message="spec.forProvider.resources is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runtime) || (has(self.initProvider) && has(self.initProvider.runtime))",message="spec.forProvider.runtime is a required parameter"
	Spec   DeploymentSpec   `json:"spec"`
	Status DeploymentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeploymentList contains a list of Deployments
type DeploymentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Deployment `json:"items"`
}

// Repository type metadata.
var (
	Deployment_Kind             = "Deployment"
	Deployment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Deployment_Kind}.String()
	Deployment_KindAPIVersion   = Deployment_Kind + "." + CRDGroupVersion.String()
	Deployment_GroupVersionKind = CRDGroupVersion.WithKind(Deployment_Kind)
)

func init() {
	SchemeBuilder.Register(&Deployment{}, &DeploymentList{})
}
