// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DHCPInitParameters struct {

	// (Attributes) Settings affecting DNS for DHCP within the VPC (see below for nested schema)
	DNS *DNSInitParameters `json:"dns,omitempty" tf:"dns,omitempty"`
}

type DHCPObservation struct {

	// (Attributes) Settings affecting DNS for DHCP within the VPC (see below for nested schema)
	DNS *DNSObservation `json:"dns,omitempty" tf:"dns,omitempty"`
}

type DHCPParameters struct {

	// (Attributes) Settings affecting DNS for DHCP within the VPC (see below for nested schema)
	// +kubebuilder:validation:Optional
	DNS *DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`
}

type DNSInitParameters struct {

	// (Set of String) The DNS servers to be used by DHCP clients within the VPC.
	// The DNS servers to be used by DHCP clients within the VPC.
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type DNSObservation struct {

	// (Set of String) The DNS servers to be used by DHCP clients within the VPC.
	// The DNS servers to be used by DHCP clients within the VPC.
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type DNSParameters struct {

	// (Set of String) The DNS servers to be used by DHCP clients within the VPC.
	// The DNS servers to be used by DHCP clients within the VPC.
	// +kubebuilder:validation:Optional
	// +listType=set
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type EgressInitParameters struct {

	// (Boolean) Specifies whether the VPC should be blocked from consuming public Internet.
	// Specifies whether the VPC should be blocked from consuming public Internet.
	DisablePublicAccess *bool `json:"disablePublicAccess,omitempty" tf:"disable_public_access,omitempty"`
}

type EgressObservation struct {

	// (Boolean) Specifies whether the VPC should be blocked from consuming public Internet.
	// Specifies whether the VPC should be blocked from consuming public Internet.
	DisablePublicAccess *bool `json:"disablePublicAccess,omitempty" tf:"disable_public_access,omitempty"`
}

type EgressParameters struct {

	// (Boolean) Specifies whether the VPC should be blocked from consuming public Internet.
	// Specifies whether the VPC should be blocked from consuming public Internet.
	// +kubebuilder:validation:Optional
	DisablePublicAccess *bool `json:"disablePublicAccess,omitempty" tf:"disable_public_access,omitempty"`
}

type HostPrefixesInitParameters struct {

	// (Attributes) The configuration for a secondary host prefix. (see below for nested schema)
	Ipam *IpamInitParameters `json:"ipam,omitempty" tf:"ipam,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The user-specified name of the host prefix.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	// The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	Prefixes []*string `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	// (String) Controls network connectivity from the prefix to the host. Must be one of: PRIMARY, ROUTED, ATTACHED.
	// Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type HostPrefixesObservation struct {

	// (Attributes) The configuration for a secondary host prefix. (see below for nested schema)
	Ipam *IpamObservation `json:"ipam,omitempty" tf:"ipam,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The user-specified name of the host prefix.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	// The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	Prefixes []*string `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	// (String) Controls network connectivity from the prefix to the host. Must be one of: PRIMARY, ROUTED, ATTACHED.
	// Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type HostPrefixesParameters struct {

	// (Attributes) The configuration for a secondary host prefix. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Ipam *IpamParameters `json:"ipam,omitempty" tf:"ipam,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The user-specified name of the host prefix.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	// The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
	// +kubebuilder:validation:Optional
	Prefixes []*string `json:"prefixes" tf:"prefixes,omitempty"`

	// (String) Controls network connectivity from the prefix to the host. Must be one of: PRIMARY, ROUTED, ATTACHED.
	// Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type IngressInitParameters struct {

	// facing networks, making them inaccessible from the Internet.
	// Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
	DisablePublicServices *bool `json:"disablePublicServices,omitempty" tf:"disable_public_services,omitempty"`
}

type IngressObservation struct {

	// facing networks, making them inaccessible from the Internet.
	// Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
	DisablePublicServices *bool `json:"disablePublicServices,omitempty" tf:"disable_public_services,omitempty"`
}

type IngressParameters struct {

	// facing networks, making them inaccessible from the Internet.
	// Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
	// +kubebuilder:validation:Optional
	DisablePublicServices *bool `json:"disablePublicServices,omitempty" tf:"disable_public_services,omitempty"`
}

type IpamInitParameters struct {

	// (String) Describes which IP address from the prefix is allocated to the network gateway. Must be one of: UNSPECIFIED, EUI64, FIRST_IP, LAST_IP.
	// Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
	GatewayAddressPolicy *string `json:"gatewayAddressPolicy,omitempty" tf:"gateway_address_policy,omitempty"`

	// wide aggregate prefix.
	// The desired length for each Node's allocation from the VPC-wide aggregate prefix.
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`
}

type IpamObservation struct {

	// (String) Describes which IP address from the prefix is allocated to the network gateway. Must be one of: UNSPECIFIED, EUI64, FIRST_IP, LAST_IP.
	// Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
	GatewayAddressPolicy *string `json:"gatewayAddressPolicy,omitempty" tf:"gateway_address_policy,omitempty"`

	// wide aggregate prefix.
	// The desired length for each Node's allocation from the VPC-wide aggregate prefix.
	PrefixLength *float64 `json:"prefixLength,omitempty" tf:"prefix_length,omitempty"`
}

type IpamParameters struct {

	// (String) Describes which IP address from the prefix is allocated to the network gateway. Must be one of: UNSPECIFIED, EUI64, FIRST_IP, LAST_IP.
	// Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
	// +kubebuilder:validation:Optional
	GatewayAddressPolicy *string `json:"gatewayAddressPolicy,omitempty" tf:"gateway_address_policy,omitempty"`

	// wide aggregate prefix.
	// The desired length for each Node's allocation from the VPC-wide aggregate prefix.
	// +kubebuilder:validation:Optional
	PrefixLength *float64 `json:"prefixLength" tf:"prefix_length,omitempty"`
}

type VPCInitParameters struct {

	// (Attributes) Settings affecting DHCP behavior within the VPC. (see below for nested schema)
	DHCP *DHCPInitParameters `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// (Attributes) Settings affecting traffic leaving the VPC. (see below for nested schema)
	Egress *EgressInitParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See Host prefixes for details. This field is immutable once set.
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC. For SUNK clusters, use a prefix no smaller than your Zone's default host prefix (a mask no longer than the default) so that host addresses reflect each node's physical location. SUNK uses this location information to place network-adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See [Host prefixes](https://docs.coreweave.com/products/networking/vpc/create-manage-vpcs#host-prefixes) for details. This field is immutable once set.
	HostPrefix *string `json:"hostPrefix,omitempty" tf:"host_prefix,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a primary host prefix (type = PRIMARY) no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. See Host prefixes for details. (see below for nested schema)
	HostPrefixes []HostPrefixesInitParameters `json:"hostPrefixes,omitempty" tf:"host_prefixes,omitempty"`

	// (Attributes) Settings affecting traffic entering the VPC. (see below for nested schema)
	Ingress *IngressInitParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The name of the VPC. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges. (see below for nested schema)
	VPCPrefixes []VPCPrefixesInitParameters `json:"vpcPrefixes,omitempty" tf:"vpc_prefixes,omitempty"`

	// (String) The Availability Zone in which the VPC is located.
	// The Availability Zone in which the VPC is located.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VPCObservation struct {

	// (Attributes) Settings affecting DHCP behavior within the VPC. (see below for nested schema)
	DHCP *DHCPObservation `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// (Attributes) Settings affecting traffic leaving the VPC. (see below for nested schema)
	Egress *EgressObservation `json:"egress,omitempty" tf:"egress,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See Host prefixes for details. This field is immutable once set.
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC. For SUNK clusters, use a prefix no smaller than your Zone's default host prefix (a mask no longer than the default) so that host addresses reflect each node's physical location. SUNK uses this location information to place network-adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See [Host prefixes](https://docs.coreweave.com/products/networking/vpc/create-manage-vpcs#host-prefixes) for details. This field is immutable once set.
	HostPrefix *string `json:"hostPrefix,omitempty" tf:"host_prefix,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a primary host prefix (type = PRIMARY) no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. See Host prefixes for details. (see below for nested schema)
	HostPrefixes []HostPrefixesObservation `json:"hostPrefixes,omitempty" tf:"host_prefixes,omitempty"`

	// (String) The unique identifier for the VPC.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Settings affecting traffic entering the VPC. (see below for nested schema)
	Ingress *IngressObservation `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The name of the VPC. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges. (see below for nested schema)
	VPCPrefixes []VPCPrefixesObservation `json:"vpcPrefixes,omitempty" tf:"vpc_prefixes,omitempty"`

	// (String) The Availability Zone in which the VPC is located.
	// The Availability Zone in which the VPC is located.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VPCParameters struct {

	// (Attributes) Settings affecting DHCP behavior within the VPC. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DHCP *DHCPParameters `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// (Attributes) Settings affecting traffic leaving the VPC. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Egress *EgressParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See Host prefixes for details. This field is immutable once set.
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC. For SUNK clusters, use a prefix no smaller than your Zone's default host prefix (a mask no longer than the default) so that host addresses reflect each node's physical location. SUNK uses this location information to place network-adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a host prefix no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. If left unspecified, a Zone-specific default value will be applied by the server. See [Host prefixes](https://docs.coreweave.com/products/networking/vpc/create-manage-vpcs#host-prefixes) for details. This field is immutable once set.
	// +kubebuilder:validation:Optional
	HostPrefix *string `json:"hostPrefix,omitempty" tf:"host_prefix,omitempty"`

	// adjacent nodes together, which improves distributed-training performance. A prefix smaller than the Zone default (a longer mask) doesn't carry this location information, so it produces less optimal placement. If you need a different size, CoreWeave can approve one for your account on request. For non-SUNK VPCs, any prefix size is accepted. However, NVL72 rack-level instances require a primary host prefix (type = PRIMARY) no smaller than the Zone's default host prefix. A smaller prefix forces dynamic address allocation, which breaks standard IMEX address mapping across the cluster. IMEX with Dynamic Resource Allocation (DRA) doesn't have this limitation. See Host prefixes for details. (see below for nested schema)
	// +kubebuilder:validation:Optional
	HostPrefixes []HostPrefixesParameters `json:"hostPrefixes,omitempty" tf:"host_prefixes,omitempty"`

	// (Attributes) Settings affecting traffic entering the VPC. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Ingress *IngressParameters `json:"ingress,omitempty" tf:"ingress,omitempty"`

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// The name of the VPC. Must not be longer than 30 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges. (see below for nested schema)
	// +kubebuilder:validation:Optional
	VPCPrefixes []VPCPrefixesParameters `json:"vpcPrefixes,omitempty" tf:"vpc_prefixes,omitempty"`

	// (String) The Availability Zone in which the VPC is located.
	// The Availability Zone in which the VPC is located.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type VPCPrefixesInitParameters struct {

	// (String) The name of the VPC. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type VPCPrefixesObservation struct {

	// (String) The name of the VPC. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type VPCPrefixesParameters struct {

	// (String) The name of the VPC. Must not be longer than 30 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// VPCSpec defines the desired state of VPC
type VPCSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   VPCParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPCInitParameters `json:"initProvider,omitempty"`
}

// VPCStatus defines the observed state of VPC.
type VPCStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VPCObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPC is the Schema for the VPCs API. Create and manage VPCs. Learn more about CoreWeave VPCs https://docs.coreweave.com/products/networking/vpc/about-vpcs.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coreweave}
type VPC struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   VPCSpec   `json:"spec"`
	Status VPCStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPCList contains a list of VPCs
type VPCList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPC `json:"items"`
}

// Repository type metadata.
var (
	VPC_Kind             = "VPC"
	VPC_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPC_Kind}.String()
	VPC_KindAPIVersion   = VPC_Kind + "." + CRDGroupVersion.String()
	VPC_GroupVersionKind = CRDGroupVersion.WithKind(VPC_Kind)
)

func init() {
	SchemeBuilder.Register(&VPC{}, &VPCList{})
}
