// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AuthnWebhookInitParameters struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type AuthnWebhookObservation struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type AuthnWebhookParameters struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	// +kubebuilder:validation:Optional
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	// +kubebuilder:validation:Optional
	Server *string `json:"server" tf:"server,omitempty"`
}

type AuthzWebhookInitParameters struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type AuthzWebhookObservation struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	Server *string `json:"server,omitempty" tf:"server,omitempty"`
}

type AuthzWebhookParameters struct {

	// encoded PEM-encoded certificate.
	// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
	// +kubebuilder:validation:Optional
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The URL of the webhook server.
	// The URL of the webhook server.
	// +kubebuilder:validation:Optional
	Server *string `json:"server" tf:"server,omitempty"`
}

type ClusterInitParameters struct {

	// (Set of String) Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// +listType=set
	AdditionalServerSans []*string `json:"additionalServerSans,omitempty" tf:"additional_server_sans,omitempty"`

	// encoded JSON/YAML string.
	// Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
	AuditPolicy *string `json:"auditPolicy,omitempty" tf:"audit_policy,omitempty"`

	// (Attributes) Authentication webhook configuration for the cluster. (see below for nested schema)
	AuthnWebhook *AuthnWebhookInitParameters `json:"authnWebhook,omitempty" tf:"authn_webhook,omitempty"`

	// (Attributes) Authorization webhook configuration for the cluster. (see below for nested schema)
	AuthzWebhook *AuthzWebhookInitParameters `json:"authzWebhook,omitempty" tf:"authz_webhook,omitempty"`

	// only.
	// The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
	// The prefixes must exist in the cluster's VPC. This field is append-only.
	InternalLBCidrNames []*string `json:"internalLbCidrNames,omitempty" tf:"internal_lb_cidr_names,omitempty"`

	// (List of String) IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	InternalLBCidrNamesV6 []*string `json:"internalLbCidrNamesV6,omitempty" tf:"internal_lb_cidr_names_v6,omitempty"`

	// (String) Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. jsonencode({ maxPods = 256 })). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the Kubernetes kubelet configuration reference for supported options.
	// Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. `jsonencode({ maxPods = 256 })`). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the [Kubernetes kubelet configuration reference](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for supported options.
	Kubelet *string `json:"kubelet,omitempty" tf:"kubelet,omitempty"`

	// (String) The name of the cluster. Must not be longer than 30 characters.
	// The name of the cluster. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster. (see below for nested schema)
	NodePortRange *NodePortRangeInitParameters `json:"nodePortRange,omitempty" tf:"node_port_range,omitempty"`

	// server. (see below for nested schema)
	Oidc *OidcInitParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (String) The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	PodCidrName *string `json:"podCidrName,omitempty" tf:"pod_cidr_name,omitempty"`

	// (String) IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	PodCidrNameV6 *string `json:"podCidrNameV6,omitempty" tf:"pod_cidr_name_v6,omitempty"`

	// server is publicly accessible from the internet.
	// Whether the cluster's api-server is publicly accessible from the internet.
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// (String) The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	ServiceCidrName *string `json:"serviceCidrName,omitempty" tf:"service_cidr_name,omitempty"`

	// (String) IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	ServiceCidrNameV6 *string `json:"serviceCidrNameV6,omitempty" tf:"service_cidr_name_v6,omitempty"`

	// (String) The cluster_id of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	// The `cluster_id` of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/cks/v1alpha1.Cluster
	// +crossplane:generate:reference:refFieldName=SharedStorageClusterRef
	// +crossplane:generate:reference:selectorFieldName=SharedStorageClusterSelector
	SharedStorageClusterID *string `json:"sharedStorageClusterId,omitempty" tf:"shared_storage_cluster_id,omitempty"`

	// Reference to a Cluster in cks to populate sharedStorageClusterId.
	// +kubebuilder:validation:Optional
	SharedStorageClusterRef *v2.NamespacedReference `json:"sharedStorageClusterRef,omitempty" tf:"-"`

	// Selector for a Cluster in cks to populate sharedStorageClusterId.
	// +kubebuilder:validation:Optional
	SharedStorageClusterSelector *v2.NamespacedSelector `json:"sharedStorageClusterSelector,omitempty" tf:"-"`

	// (Attributes) Tailscale configuration for the cluster. Enables cluster access via a Tailscale VPN. (see below for nested schema)
	Tailscale *TailscaleInitParameters `json:"tailscale,omitempty" tf:"tailscale,omitempty"`

	// (String) The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	// The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/networking/v1alpha1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in networking to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in networking to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`

	// (String) The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	// The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) The Availability Zone in which the cluster is located.
	// The Availability Zone in which the cluster is located.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ClusterObservation struct {

	// server.
	// The endpoint for the cluster's api-server.
	APIServerEndpoint *string `json:"apiServerEndpoint,omitempty" tf:"api_server_endpoint,omitempty"`

	// (Set of String) Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// +listType=set
	AdditionalServerSans []*string `json:"additionalServerSans,omitempty" tf:"additional_server_sans,omitempty"`

	// encoded JSON/YAML string.
	// Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
	AuditPolicy *string `json:"auditPolicy,omitempty" tf:"audit_policy,omitempty"`

	// (Attributes) Authentication webhook configuration for the cluster. (see below for nested schema)
	AuthnWebhook *AuthnWebhookObservation `json:"authnWebhook,omitempty" tf:"authn_webhook,omitempty"`

	// (Attributes) Authorization webhook configuration for the cluster. (see below for nested schema)
	AuthzWebhook *AuthzWebhookObservation `json:"authzWebhook,omitempty" tf:"authz_webhook,omitempty"`

	// (String) The unique identifier of the cluster.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// only.
	// The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
	// The prefixes must exist in the cluster's VPC. This field is append-only.
	InternalLBCidrNames []*string `json:"internalLbCidrNames,omitempty" tf:"internal_lb_cidr_names,omitempty"`

	// (List of String) IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	InternalLBCidrNamesV6 []*string `json:"internalLbCidrNamesV6,omitempty" tf:"internal_lb_cidr_names_v6,omitempty"`

	// (String) Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. jsonencode({ maxPods = 256 })). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the Kubernetes kubelet configuration reference for supported options.
	// Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. `jsonencode({ maxPods = 256 })`). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the [Kubernetes kubelet configuration reference](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for supported options.
	Kubelet *string `json:"kubelet,omitempty" tf:"kubelet,omitempty"`

	// (String) The name of the cluster. Must not be longer than 30 characters.
	// The name of the cluster. Must not be longer than 30 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster. (see below for nested schema)
	NodePortRange *NodePortRangeObservation `json:"nodePortRange,omitempty" tf:"node_port_range,omitempty"`

	// server. (see below for nested schema)
	Oidc *OidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (String) The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	PodCidrName *string `json:"podCidrName,omitempty" tf:"pod_cidr_name,omitempty"`

	// (String) IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	PodCidrNameV6 *string `json:"podCidrNameV6,omitempty" tf:"pod_cidr_name_v6,omitempty"`

	// server is publicly accessible from the internet.
	// Whether the cluster's api-server is publicly accessible from the internet.
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// -service-account-issuer flag on the kube-apiserver.
	// The URL of the OIDC issuer for the cluster's service account tokens. This value corresponds to the `--service-account-issuer` flag on the kube-apiserver.
	ServiceAccountOidcIssuerURL *string `json:"serviceAccountOidcIssuerUrl,omitempty" tf:"service_account_oidc_issuer_url,omitempty"`

	// (String) The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	ServiceCidrName *string `json:"serviceCidrName,omitempty" tf:"service_cidr_name,omitempty"`

	// (String) IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	ServiceCidrNameV6 *string `json:"serviceCidrNameV6,omitempty" tf:"service_cidr_name_v6,omitempty"`

	// (String) The cluster_id of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	// The `cluster_id` of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	SharedStorageClusterID *string `json:"sharedStorageClusterId,omitempty" tf:"shared_storage_cluster_id,omitempty"`

	// (String) The current status of the cluster.
	// The current status of the cluster.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Attributes) Tailscale configuration for the cluster. Enables cluster access via a Tailscale VPN. (see below for nested schema)
	Tailscale *TailscaleObservation `json:"tailscale,omitempty" tf:"tailscale,omitempty"`

	// (String) The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	// The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// (String) The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	// The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) The Availability Zone in which the cluster is located.
	// The Availability Zone in which the cluster is located.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ClusterParameters struct {

	// (Set of String) Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
	// +kubebuilder:validation:Optional
	// +listType=set
	AdditionalServerSans []*string `json:"additionalServerSans,omitempty" tf:"additional_server_sans,omitempty"`

	// encoded JSON/YAML string.
	// Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
	// +kubebuilder:validation:Optional
	AuditPolicy *string `json:"auditPolicy,omitempty" tf:"audit_policy,omitempty"`

	// (Attributes) Authentication webhook configuration for the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuthnWebhook *AuthnWebhookParameters `json:"authnWebhook,omitempty" tf:"authn_webhook,omitempty"`

	// (Attributes) Authorization webhook configuration for the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuthzWebhook *AuthzWebhookParameters `json:"authzWebhook,omitempty" tf:"authz_webhook,omitempty"`

	// only.
	// The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
	// The prefixes must exist in the cluster's VPC. This field is append-only.
	// +kubebuilder:validation:Optional
	InternalLBCidrNames []*string `json:"internalLbCidrNames,omitempty" tf:"internal_lb_cidr_names,omitempty"`

	// (List of String) IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// +kubebuilder:validation:Optional
	InternalLBCidrNamesV6 []*string `json:"internalLbCidrNamesV6,omitempty" tf:"internal_lb_cidr_names_v6,omitempty"`

	// (String) Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. jsonencode({ maxPods = 256 })). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the Kubernetes kubelet configuration reference for supported options.
	// Selective overrides applied to every cluster Node's kubelet configuration, as a JSON object (e.g. `jsonencode({ maxPods = 256 })`). A Node reboot is required for changes to take effect, and unknown options are stored but ignored by CKS. See the [Kubernetes kubelet configuration reference](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) for supported options.
	// +kubebuilder:validation:Optional
	Kubelet *string `json:"kubelet,omitempty" tf:"kubelet,omitempty"`

	// (String) The name of the cluster. Must not be longer than 30 characters.
	// The name of the cluster. Must not be longer than 30 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NodePortRange *NodePortRangeParameters `json:"nodePortRange,omitempty" tf:"node_port_range,omitempty"`

	// server. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Oidc *OidcParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// (String) The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
	// +kubebuilder:validation:Optional
	PodCidrName *string `json:"podCidrName,omitempty" tf:"pod_cidr_name,omitempty"`

	// (String) IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// +kubebuilder:validation:Optional
	PodCidrNameV6 *string `json:"podCidrNameV6,omitempty" tf:"pod_cidr_name_v6,omitempty"`

	// server is publicly accessible from the internet.
	// Whether the cluster's api-server is publicly accessible from the internet.
	// +kubebuilder:validation:Optional
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// (String) The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	// The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
	// +kubebuilder:validation:Optional
	ServiceCidrName *string `json:"serviceCidrName,omitempty" tf:"service_cidr_name,omitempty"`

	// (String) IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
	// +kubebuilder:validation:Optional
	ServiceCidrNameV6 *string `json:"serviceCidrNameV6,omitempty" tf:"service_cidr_name_v6,omitempty"`

	// (String) The cluster_id of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	// The `cluster_id` of the cluster to share storage with. Must be enabled by CoreWeave support. Contact CoreWeave support if you are interested in this feature.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/cks/v1alpha1.Cluster
	// +crossplane:generate:reference:refFieldName=SharedStorageClusterRef
	// +crossplane:generate:reference:selectorFieldName=SharedStorageClusterSelector
	// +kubebuilder:validation:Optional
	SharedStorageClusterID *string `json:"sharedStorageClusterId,omitempty" tf:"shared_storage_cluster_id,omitempty"`

	// Reference to a Cluster in cks to populate sharedStorageClusterId.
	// +kubebuilder:validation:Optional
	SharedStorageClusterRef *v2.NamespacedReference `json:"sharedStorageClusterRef,omitempty" tf:"-"`

	// Selector for a Cluster in cks to populate sharedStorageClusterId.
	// +kubebuilder:validation:Optional
	SharedStorageClusterSelector *v2.NamespacedSelector `json:"sharedStorageClusterSelector,omitempty" tf:"-"`

	// (Attributes) Tailscale configuration for the cluster. Enables cluster access via a Tailscale VPN. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Tailscale *TailscaleParameters `json:"tailscale,omitempty" tf:"tailscale,omitempty"`

	// (String) The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	// The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
	// +crossplane:generate:reference:type=github.com/fabioaraujopt/provider-coreweave/apis/namespaced/networking/v1alpha1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in networking to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.NamespacedReference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in networking to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.NamespacedSelector `json:"vpcIdSelector,omitempty" tf:"-"`

	// (String) The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	// The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// (String) The Availability Zone in which the cluster is located.
	// The Availability Zone in which the cluster is located.
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type NodePortRangeInitParameters struct {

	// (Number)
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Number)
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type NodePortRangeObservation struct {

	// (Number)
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Number)
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type NodePortRangeParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type OidcInitParameters struct {

	// admin role for bootstrap access to the cluster.
	// The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
	AdminGroupBinding *string `json:"adminGroupBinding,omitempty" tf:"admin_group_binding,omitempty"`

	// encoded PEM-encoded certificate.
	// The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The client ID for the OIDC client.
	// The client ID for the OIDC client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The claim to use as the groups.
	// The claim to use as the groups.
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) The prefix to use for the groups.
	// The prefix to use for the groups.
	GroupsPrefix *string `json:"groupsPrefix,omitempty" tf:"groups_prefix,omitempty"`

	// (String) The URL of the OIDC issuer.
	// The URL of the OIDC issuer.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// (String) The claim to require for authentication.
	// The claim to require for authentication.
	RequiredClaim *string `json:"requiredClaim,omitempty" tf:"required_claim,omitempty"`

	// (Set of String) A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// +listType=set
	SigningAlgs []*string `json:"signingAlgs,omitempty" tf:"signing_algs,omitempty"`

	// (String) The claim to use as the username.
	// The claim to use as the username.
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// (String) The prefix to use for the username.
	// The prefix to use for the username.
	UsernamePrefix *string `json:"usernamePrefix,omitempty" tf:"username_prefix,omitempty"`
}

type OidcObservation struct {

	// admin role for bootstrap access to the cluster.
	// The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
	AdminGroupBinding *string `json:"adminGroupBinding,omitempty" tf:"admin_group_binding,omitempty"`

	// encoded PEM-encoded certificate.
	// The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The client ID for the OIDC client.
	// The client ID for the OIDC client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The claim to use as the groups.
	// The claim to use as the groups.
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) The prefix to use for the groups.
	// The prefix to use for the groups.
	GroupsPrefix *string `json:"groupsPrefix,omitempty" tf:"groups_prefix,omitempty"`

	// (String) The URL of the OIDC issuer.
	// The URL of the OIDC issuer.
	IssuerURL *string `json:"issuerUrl,omitempty" tf:"issuer_url,omitempty"`

	// (String) The claim to require for authentication.
	// The claim to require for authentication.
	RequiredClaim *string `json:"requiredClaim,omitempty" tf:"required_claim,omitempty"`

	// (Set of String) A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// +listType=set
	SigningAlgs []*string `json:"signingAlgs,omitempty" tf:"signing_algs,omitempty"`

	// (String) The claim to use as the username.
	// The claim to use as the username.
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// (String) The prefix to use for the username.
	// The prefix to use for the username.
	UsernamePrefix *string `json:"usernamePrefix,omitempty" tf:"username_prefix,omitempty"`
}

type OidcParameters struct {

	// admin role for bootstrap access to the cluster.
	// The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
	// +kubebuilder:validation:Optional
	AdminGroupBinding *string `json:"adminGroupBinding,omitempty" tf:"admin_group_binding,omitempty"`

	// encoded PEM-encoded certificate.
	// The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
	// +kubebuilder:validation:Optional
	CA *string `json:"ca,omitempty" tf:"ca,omitempty"`

	// (String) The client ID for the OIDC client.
	// The client ID for the OIDC client.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`

	// (String) The claim to use as the groups.
	// The claim to use as the groups.
	// +kubebuilder:validation:Optional
	GroupsClaim *string `json:"groupsClaim,omitempty" tf:"groups_claim,omitempty"`

	// (String) The prefix to use for the groups.
	// The prefix to use for the groups.
	// +kubebuilder:validation:Optional
	GroupsPrefix *string `json:"groupsPrefix,omitempty" tf:"groups_prefix,omitempty"`

	// (String) The URL of the OIDC issuer.
	// The URL of the OIDC issuer.
	// +kubebuilder:validation:Optional
	IssuerURL *string `json:"issuerUrl" tf:"issuer_url,omitempty"`

	// (String) The claim to require for authentication.
	// The claim to require for authentication.
	// +kubebuilder:validation:Optional
	RequiredClaim *string `json:"requiredClaim,omitempty" tf:"required_claim,omitempty"`

	// (Set of String) A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// A list of signing algorithms that the OpenID Connect discovery endpoint uses.
	// +kubebuilder:validation:Optional
	// +listType=set
	SigningAlgs []*string `json:"signingAlgs,omitempty" tf:"signing_algs,omitempty"`

	// (String) The claim to use as the username.
	// The claim to use as the username.
	// +kubebuilder:validation:Optional
	UsernameClaim *string `json:"usernameClaim,omitempty" tf:"username_claim,omitempty"`

	// (String) The prefix to use for the username.
	// The prefix to use for the username.
	// +kubebuilder:validation:Optional
	UsernamePrefix *string `json:"usernamePrefix,omitempty" tf:"username_prefix,omitempty"`
}

type TailscaleInitParameters struct {

	// (String) The client ID for the OIDC client.
	// The Tailscale Client ID for the federated identity.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`
}

type TailscaleObservation struct {

	// (String) The client ID for the OIDC client.
	// The Tailscale Client ID for the federated identity.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`
}

type TailscaleParameters struct {

	// (String) The client ID for the OIDC client.
	// The Tailscale Client ID for the federated identity.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId" tf:"client_id,omitempty"`
}

// ClusterSpec defines the desired state of Cluster
type ClusterSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ClusterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClusterInitParameters `json:"initProvider,omitempty"`
}

// ClusterStatus defines the observed state of Cluster.
type ClusterStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ClusterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cluster is the Schema for the Clusters API. Create and manage clusters on CoreWeave Kubernetes Service (CKS) https://docs.coreweave.com/products/cks/clusters/introduction.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,coreweave}
type Cluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.internalLbCidrNames) || (has(self.initProvider) && has(self.initProvider.internalLbCidrNames))",message="spec.forProvider.internalLbCidrNames is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.podCidrName) || (has(self.initProvider) && has(self.initProvider.podCidrName))",message="spec.forProvider.podCidrName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceCidrName) || (has(self.initProvider) && has(self.initProvider.serviceCidrName))",message="spec.forProvider.serviceCidrName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zone) || (has(self.initProvider) && has(self.initProvider.zone))",message="spec.forProvider.zone is a required parameter"
	Spec   ClusterSpec   `json:"spec"`
	Status ClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterList contains a list of Clusters
type ClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cluster `json:"items"`
}

// Repository type metadata.
var (
	Cluster_Kind             = "Cluster"
	Cluster_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cluster_Kind}.String()
	Cluster_KindAPIVersion   = Cluster_Kind + "." + CRDGroupVersion.String()
	Cluster_GroupVersionKind = CRDGroupVersion.WithKind(Cluster_Kind)
)

func init() {
	SchemeBuilder.Register(&Cluster{}, &ClusterList{})
}
