//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthnWebhookInitParameters) DeepCopyInto(out *AuthnWebhookInitParameters) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthnWebhookInitParameters.
func (in *AuthnWebhookInitParameters) DeepCopy() *AuthnWebhookInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthnWebhookInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthnWebhookObservation) DeepCopyInto(out *AuthnWebhookObservation) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthnWebhookObservation.
func (in *AuthnWebhookObservation) DeepCopy() *AuthnWebhookObservation {
	if in == nil {
		return nil
	}
	out := new(AuthnWebhookObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthnWebhookParameters) DeepCopyInto(out *AuthnWebhookParameters) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthnWebhookParameters.
func (in *AuthnWebhookParameters) DeepCopy() *AuthnWebhookParameters {
	if in == nil {
		return nil
	}
	out := new(AuthnWebhookParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthzWebhookInitParameters) DeepCopyInto(out *AuthzWebhookInitParameters) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthzWebhookInitParameters.
func (in *AuthzWebhookInitParameters) DeepCopy() *AuthzWebhookInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthzWebhookInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthzWebhookObservation) DeepCopyInto(out *AuthzWebhookObservation) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthzWebhookObservation.
func (in *AuthzWebhookObservation) DeepCopy() *AuthzWebhookObservation {
	if in == nil {
		return nil
	}
	out := new(AuthzWebhookObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthzWebhookParameters) DeepCopyInto(out *AuthzWebhookParameters) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthzWebhookParameters.
func (in *AuthzWebhookParameters) DeepCopy() *AuthzWebhookParameters {
	if in == nil {
		return nil
	}
	out := new(AuthzWebhookParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInitParameters) DeepCopyInto(out *ClusterInitParameters) {
	*out = *in
	if in.AdditionalServerSans != nil {
		in, out := &in.AdditionalServerSans, &out.AdditionalServerSans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuditPolicy != nil {
		in, out := &in.AuditPolicy, &out.AuditPolicy
		*out = new(string)
		**out = **in
	}
	if in.AuthnWebhook != nil {
		in, out := &in.AuthnWebhook, &out.AuthnWebhook
		*out = new(AuthnWebhookInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthzWebhook != nil {
		in, out := &in.AuthzWebhook, &out.AuthzWebhook
		*out = new(AuthzWebhookInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalLBCidrNames != nil {
		in, out := &in.InternalLBCidrNames, &out.InternalLBCidrNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InternalLBCidrNamesV6 != nil {
		in, out := &in.InternalLBCidrNamesV6, &out.InternalLBCidrNamesV6
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Kubelet != nil {
		in, out := &in.Kubelet, &out.Kubelet
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodePortRange != nil {
		in, out := &in.NodePortRange, &out.NodePortRange
		*out = new(NodePortRangeInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = new(OidcInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PodCidrName != nil {
		in, out := &in.PodCidrName, &out.PodCidrName
		*out = new(string)
		**out = **in
	}
	if in.PodCidrNameV6 != nil {
		in, out := &in.PodCidrNameV6, &out.PodCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.ServiceCidrName != nil {
		in, out := &in.ServiceCidrName, &out.ServiceCidrName
		*out = new(string)
		**out = **in
	}
	if in.ServiceCidrNameV6 != nil {
		in, out := &in.ServiceCidrNameV6, &out.ServiceCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.SharedStorageClusterID != nil {
		in, out := &in.SharedStorageClusterID, &out.SharedStorageClusterID
		*out = new(string)
		**out = **in
	}
	if in.SharedStorageClusterRef != nil {
		in, out := &in.SharedStorageClusterRef, &out.SharedStorageClusterRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedStorageClusterSelector != nil {
		in, out := &in.SharedStorageClusterSelector, &out.SharedStorageClusterSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tailscale != nil {
		in, out := &in.Tailscale, &out.Tailscale
		*out = new(TailscaleInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInitParameters.
func (in *ClusterInitParameters) DeepCopy() *ClusterInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterObservation) DeepCopyInto(out *ClusterObservation) {
	*out = *in
	if in.APIServerEndpoint != nil {
		in, out := &in.APIServerEndpoint, &out.APIServerEndpoint
		*out = new(string)
		**out = **in
	}
	if in.AdditionalServerSans != nil {
		in, out := &in.AdditionalServerSans, &out.AdditionalServerSans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuditPolicy != nil {
		in, out := &in.AuditPolicy, &out.AuditPolicy
		*out = new(string)
		**out = **in
	}
	if in.AuthnWebhook != nil {
		in, out := &in.AuthnWebhook, &out.AuthnWebhook
		*out = new(AuthnWebhookObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthzWebhook != nil {
		in, out := &in.AuthzWebhook, &out.AuthzWebhook
		*out = new(AuthzWebhookObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InternalLBCidrNames != nil {
		in, out := &in.InternalLBCidrNames, &out.InternalLBCidrNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InternalLBCidrNamesV6 != nil {
		in, out := &in.InternalLBCidrNamesV6, &out.InternalLBCidrNamesV6
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Kubelet != nil {
		in, out := &in.Kubelet, &out.Kubelet
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodePortRange != nil {
		in, out := &in.NodePortRange, &out.NodePortRange
		*out = new(NodePortRangeObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = new(OidcObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.PodCidrName != nil {
		in, out := &in.PodCidrName, &out.PodCidrName
		*out = new(string)
		**out = **in
	}
	if in.PodCidrNameV6 != nil {
		in, out := &in.PodCidrNameV6, &out.PodCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.ServiceAccountOidcIssuerURL != nil {
		in, out := &in.ServiceAccountOidcIssuerURL, &out.ServiceAccountOidcIssuerURL
		*out = new(string)
		**out = **in
	}
	if in.ServiceCidrName != nil {
		in, out := &in.ServiceCidrName, &out.ServiceCidrName
		*out = new(string)
		**out = **in
	}
	if in.ServiceCidrNameV6 != nil {
		in, out := &in.ServiceCidrNameV6, &out.ServiceCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.SharedStorageClusterID != nil {
		in, out := &in.SharedStorageClusterID, &out.SharedStorageClusterID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tailscale != nil {
		in, out := &in.Tailscale, &out.Tailscale
		*out = new(TailscaleObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterObservation.
func (in *ClusterObservation) DeepCopy() *ClusterObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterParameters) DeepCopyInto(out *ClusterParameters) {
	*out = *in
	if in.AdditionalServerSans != nil {
		in, out := &in.AdditionalServerSans, &out.AdditionalServerSans
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuditPolicy != nil {
		in, out := &in.AuditPolicy, &out.AuditPolicy
		*out = new(string)
		**out = **in
	}
	if in.AuthnWebhook != nil {
		in, out := &in.AuthnWebhook, &out.AuthnWebhook
		*out = new(AuthnWebhookParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthzWebhook != nil {
		in, out := &in.AuthzWebhook, &out.AuthzWebhook
		*out = new(AuthzWebhookParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalLBCidrNames != nil {
		in, out := &in.InternalLBCidrNames, &out.InternalLBCidrNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.InternalLBCidrNamesV6 != nil {
		in, out := &in.InternalLBCidrNamesV6, &out.InternalLBCidrNamesV6
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Kubelet != nil {
		in, out := &in.Kubelet, &out.Kubelet
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NodePortRange != nil {
		in, out := &in.NodePortRange, &out.NodePortRange
		*out = new(NodePortRangeParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = new(OidcParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.PodCidrName != nil {
		in, out := &in.PodCidrName, &out.PodCidrName
		*out = new(string)
		**out = **in
	}
	if in.PodCidrNameV6 != nil {
		in, out := &in.PodCidrNameV6, &out.PodCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.Public != nil {
		in, out := &in.Public, &out.Public
		*out = new(bool)
		**out = **in
	}
	if in.ServiceCidrName != nil {
		in, out := &in.ServiceCidrName, &out.ServiceCidrName
		*out = new(string)
		**out = **in
	}
	if in.ServiceCidrNameV6 != nil {
		in, out := &in.ServiceCidrNameV6, &out.ServiceCidrNameV6
		*out = new(string)
		**out = **in
	}
	if in.SharedStorageClusterID != nil {
		in, out := &in.SharedStorageClusterID, &out.SharedStorageClusterID
		*out = new(string)
		**out = **in
	}
	if in.SharedStorageClusterRef != nil {
		in, out := &in.SharedStorageClusterRef, &out.SharedStorageClusterRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SharedStorageClusterSelector != nil {
		in, out := &in.SharedStorageClusterSelector, &out.SharedStorageClusterSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tailscale != nil {
		in, out := &in.Tailscale, &out.Tailscale
		*out = new(TailscaleParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterParameters.
func (in *ClusterParameters) DeepCopy() *ClusterParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePortRangeInitParameters) DeepCopyInto(out *NodePortRangeInitParameters) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(float64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePortRangeInitParameters.
func (in *NodePortRangeInitParameters) DeepCopy() *NodePortRangeInitParameters {
	if in == nil {
		return nil
	}
	out := new(NodePortRangeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePortRangeObservation) DeepCopyInto(out *NodePortRangeObservation) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(float64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePortRangeObservation.
func (in *NodePortRangeObservation) DeepCopy() *NodePortRangeObservation {
	if in == nil {
		return nil
	}
	out := new(NodePortRangeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePortRangeParameters) DeepCopyInto(out *NodePortRangeParameters) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(float64)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePortRangeParameters.
func (in *NodePortRangeParameters) DeepCopy() *NodePortRangeParameters {
	if in == nil {
		return nil
	}
	out := new(NodePortRangeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcInitParameters) DeepCopyInto(out *OidcInitParameters) {
	*out = *in
	if in.AdminGroupBinding != nil {
		in, out := &in.AdminGroupBinding, &out.AdminGroupBinding
		*out = new(string)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgs != nil {
		in, out := &in.SigningAlgs, &out.SigningAlgs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcInitParameters.
func (in *OidcInitParameters) DeepCopy() *OidcInitParameters {
	if in == nil {
		return nil
	}
	out := new(OidcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcObservation) DeepCopyInto(out *OidcObservation) {
	*out = *in
	if in.AdminGroupBinding != nil {
		in, out := &in.AdminGroupBinding, &out.AdminGroupBinding
		*out = new(string)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgs != nil {
		in, out := &in.SigningAlgs, &out.SigningAlgs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcObservation.
func (in *OidcObservation) DeepCopy() *OidcObservation {
	if in == nil {
		return nil
	}
	out := new(OidcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcParameters) DeepCopyInto(out *OidcParameters) {
	*out = *in
	if in.AdminGroupBinding != nil {
		in, out := &in.AdminGroupBinding, &out.AdminGroupBinding
		*out = new(string)
		**out = **in
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.GroupsClaim != nil {
		in, out := &in.GroupsClaim, &out.GroupsClaim
		*out = new(string)
		**out = **in
	}
	if in.GroupsPrefix != nil {
		in, out := &in.GroupsPrefix, &out.GroupsPrefix
		*out = new(string)
		**out = **in
	}
	if in.IssuerURL != nil {
		in, out := &in.IssuerURL, &out.IssuerURL
		*out = new(string)
		**out = **in
	}
	if in.RequiredClaim != nil {
		in, out := &in.RequiredClaim, &out.RequiredClaim
		*out = new(string)
		**out = **in
	}
	if in.SigningAlgs != nil {
		in, out := &in.SigningAlgs, &out.SigningAlgs
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UsernameClaim != nil {
		in, out := &in.UsernameClaim, &out.UsernameClaim
		*out = new(string)
		**out = **in
	}
	if in.UsernamePrefix != nil {
		in, out := &in.UsernamePrefix, &out.UsernamePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcParameters.
func (in *OidcParameters) DeepCopy() *OidcParameters {
	if in == nil {
		return nil
	}
	out := new(OidcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleInitParameters) DeepCopyInto(out *TailscaleInitParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleInitParameters.
func (in *TailscaleInitParameters) DeepCopy() *TailscaleInitParameters {
	if in == nil {
		return nil
	}
	out := new(TailscaleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleObservation) DeepCopyInto(out *TailscaleObservation) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleObservation.
func (in *TailscaleObservation) DeepCopy() *TailscaleObservation {
	if in == nil {
		return nil
	}
	out := new(TailscaleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailscaleParameters) DeepCopyInto(out *TailscaleParameters) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailscaleParameters.
func (in *TailscaleParameters) DeepCopy() *TailscaleParameters {
	if in == nil {
		return nil
	}
	out := new(TailscaleParameters)
	in.DeepCopyInto(out)
	return out
}
