apiVersion: objectstorage.coreweave.crossplane.io/v1alpha1
kind: BucketLifecycleConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    rule:
    - expiration:
      - days: 30
      filter:
      - and:
        - objectSizeGreaterThan: 1000000
          prefix: logs/
          tags:
            env: prod
      id: cleanup-logs
      noncurrentVersionExpiration:
      - newerNoncurrentVersions: 2
        noncurrentDays: 7
      status: Enabled
    - abortIncompleteMultipartUpload:
      - daysAfterInitiation: 5
      expiration:
      - date: "2026-01-01T00:00:00Z"
      filter:
      - prefix: traces/
      id: expire-traces
      status: Enabled

---

apiVersion: objectstorage.coreweave.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    zone: US-EAST-04A

---

apiVersion: objectstorage.coreweave.crossplane.io/v1alpha1
kind: BucketVersioning
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketlifecycleconfiguration
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    versioningConfiguration:
    - status: Enabled
