apiVersion: objectstorage.coreweave.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    tags:
      foo: bar
    zone: US-EAST-04A
