apiVersion: objectstorage.coreweave.crossplane.io/v1alpha1
kind: OrganizationAccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/organizationaccesspolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    statements:
    - actions:
      - s3:*
      - cwobject:*
      effect: Allow
      name: allow-full-s3-api-access-to-all
      principals:
      - '*'
      resources:
      - '*'
