apiVersion: workloadfederation.coreweave.crossplane.io/v1alpha1
kind: OIDCConfig
metadata:
  name: example
spec:
  forProvider:
    name: crossplane-example
    description: Example workload identity federation
    issuerUrl: https://token.actions.githubusercontent.com
    audience: https://coreweave.com/iam
  providerConfigRef:
    name: default
