apiVersion: inference.coreweave.m.crossplane.io/v1alpha1
kind: CapacityClaim
metadata:
  annotations:
    meta.upbound.io/example-id: inference/v1alpha1/capacityclaim
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    name: my-capacity-claim
    resources:
      capacityType: CAPACITY_TYPE_MANAGED
      instanceCount: 2
      instanceType: h100-80gb-sxm5
      zones:
      - US-EAST-04A
