apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: AccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/accesskey
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    attributes:
      application: training
    durationSeconds: 0
