apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: BucketSettings
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketsettings
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    archiveAfterLastAccessDays: 60
    archiveEnabled: true
    auditLoggingEnabled: true
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketsettings
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    zone: US-EAST-04A
