apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: raw
  name: raw
  namespace: crossplane-system
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: raw
    policy: ${jsonencode(local.bucket_policy)}

---

apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: doc
  name: doc
  namespace: crossplane-system
spec:
  forProvider:
    zone: US-EAST-04A

---

apiVersion: objectstorage.coreweave.m.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucketpolicy
  labels:
    testing.upbound.io/example-name: raw
  name: raw
  namespace: crossplane-system
spec:
  forProvider:
    zone: US-EAST-04A
