// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type CapacityClaimInitParameters struct {

	// (String) The name of the capacity claim. Must be a valid hostname label.
	// The name of the capacity claim. Must be a valid hostname label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Resource configuration for the capacity claim. (see below for nested schema)
	Resources *ResourcesInitParameters `json:"resources,omitempty" tf:"resources,omitempty"`
}

type CapacityClaimObservation struct {

	// (Number) The number of instances currently allocated.
	// The number of instances currently allocated.
	AllocatedInstances *float64 `json:"allocatedInstances,omitempty" tf:"allocated_instances,omitempty"`

	// (Attributes List) Detailed status conditions for the capacity claim. (see below for nested schema)
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (String) RFC3339 timestamp of when the capacity claim was created.
	// RFC3339 timestamp of when the capacity claim was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The unique identifier of the capacity claim.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the capacity claim. Must be a valid hostname label.
	// The name of the capacity claim. Must be a valid hostname label.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that owns the capacity claim.
	// The organization ID that owns the capacity claim.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Number) The number of instances pending allocation.
	// The number of instances pending allocation.
	PendingInstances *float64 `json:"pendingInstances,omitempty" tf:"pending_instances,omitempty"`

	// (Attributes) Resource configuration for the capacity claim. (see below for nested schema)
	Resources *ResourcesObservation `json:"resources,omitempty" tf:"resources,omitempty"`

	// (String) The current status of the capacity claim. See the Inference API overview for status values.
	// The current status of the capacity claim. See the [Inference API overview](https://docs.coreweave.com/products/inference/reference/api-overview#status-values) for status values.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) RFC3339 timestamp of when the capacity claim was last updated.
	// RFC3339 timestamp of when the capacity claim was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type CapacityClaimParameters struct {

	// (String) The name of the capacity claim. Must be a valid hostname label.
	// The name of the capacity claim. Must be a valid hostname label.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) Resource configuration for the capacity claim. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Resources *ResourcesParameters `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ConditionsInitParameters struct {
}

type ConditionsObservation struct {

	// (String) RFC3339 timestamp of the last condition transition.
	// RFC3339 timestamp of the last condition transition.
	LastUpdateTime *string `json:"lastUpdateTime,omitempty" tf:"last_update_time,omitempty"`

	// readable message about the condition's last transition.
	// A human-readable message about the condition's last transition.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// readable reason for the condition's last transition.
	// A short, machine-readable reason for the condition's last transition.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// (String) The current status of the capacity claim. See the Inference API overview for status values.
	// The condition status (`True`, `False`, or `Unknown`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The condition type (e.g. Ready, Progressing).
	// The condition type (e.g. `Ready`, `Progressing`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConditionsParameters struct {
}

type ResourcesInitParameters struct {

	// (String) The capacity type for the capacity claim. Must be CAPACITY_TYPE_MANAGED.
	// The [capacity type](https://docs.coreweave.com/products/inference/scaling#capacity-claims) for the capacity claim. Must be `CAPACITY_TYPE_MANAGED`.
	CapacityType *string `json:"capacityType,omitempty" tf:"capacity_type,omitempty"`

	// (Number) The number of instances to reserve. Must be at least 1.
	// The number of instances to reserve. Must be at least 1.
	InstanceCount *float64 `json:"instanceCount,omitempty" tf:"instance_count,omitempty"`

	// 4x). Case-sensitive.
	// The instance type to reserve (e.g. `gb200-4x`). Case-sensitive.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// WEST-04A), case-sensitive. At least one is required.
	// The availability zones where the capacity claim may use resources from (e.g. `US-WEST-04A`), case-sensitive. At least one is required.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type ResourcesObservation struct {

	// (String) The capacity type for the capacity claim. Must be CAPACITY_TYPE_MANAGED.
	// The [capacity type](https://docs.coreweave.com/products/inference/scaling#capacity-claims) for the capacity claim. Must be `CAPACITY_TYPE_MANAGED`.
	CapacityType *string `json:"capacityType,omitempty" tf:"capacity_type,omitempty"`

	// (Number) The number of instances to reserve. Must be at least 1.
	// The number of instances to reserve. Must be at least 1.
	InstanceCount *float64 `json:"instanceCount,omitempty" tf:"instance_count,omitempty"`

	// 4x). Case-sensitive.
	// The instance type to reserve (e.g. `gb200-4x`). Case-sensitive.
	InstanceType *string `json:"instanceType,omitempty" tf:"instance_type,omitempty"`

	// WEST-04A), case-sensitive. At least one is required.
	// The availability zones where the capacity claim may use resources from (e.g. `US-WEST-04A`), case-sensitive. At least one is required.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type ResourcesParameters struct {

	// (String) The capacity type for the capacity claim. Must be CAPACITY_TYPE_MANAGED.
	// The [capacity type](https://docs.coreweave.com/products/inference/scaling#capacity-claims) for the capacity claim. Must be `CAPACITY_TYPE_MANAGED`.
	// +kubebuilder:validation:Optional
	CapacityType *string `json:"capacityType" tf:"capacity_type,omitempty"`

	// (Number) The number of instances to reserve. Must be at least 1.
	// The number of instances to reserve. Must be at least 1.
	// +kubebuilder:validation:Optional
	InstanceCount *float64 `json:"instanceCount" tf:"instance_count,omitempty"`

	// 4x). Case-sensitive.
	// The instance type to reserve (e.g. `gb200-4x`). Case-sensitive.
	// +kubebuilder:validation:Optional
	InstanceType *string `json:"instanceType" tf:"instance_type,omitempty"`

	// WEST-04A), case-sensitive. At least one is required.
	// The availability zones where the capacity claim may use resources from (e.g. `US-WEST-04A`), case-sensitive. At least one is required.
	// +kubebuilder:validation:Optional
	// +listType=set
	Zones []*string `json:"zones" tf:"zones,omitempty"`
}

// CapacityClaimSpec defines the desired state of CapacityClaim
type CapacityClaimSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   CapacityClaimParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CapacityClaimInitParameters `json:"initProvider,omitempty"`
}

// CapacityClaimStatus defines the observed state of CapacityClaim.
type CapacityClaimStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               CapacityClaimObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CapacityClaim is the Schema for the CapacityClaims API. Create and manage CoreWeave Managed Inference https://docs.coreweave.com/products/inference capacity claims for Dedicated Inference https://docs.coreweave.com/products/inference/dedicated. See capacity claims https://docs.coreweave.com/products/inference/scaling#capacity-claims for capacity type details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coreweave}
type CapacityClaim struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.resources) || (has(self.initProvider) && has(self.initProvider.resources))",message="spec.forProvider.resources is a required parameter"
	Spec   CapacityClaimSpec   `json:"spec"`
	Status CapacityClaimStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CapacityClaimList contains a list of CapacityClaims
type CapacityClaimList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CapacityClaim `json:"items"`
}

// Repository type metadata.
var (
	CapacityClaim_Kind             = "CapacityClaim"
	CapacityClaim_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CapacityClaim_Kind}.String()
	CapacityClaim_KindAPIVersion   = CapacityClaim_Kind + "." + CRDGroupVersion.String()
	CapacityClaim_GroupVersionKind = CRDGroupVersion.WithKind(CapacityClaim_Kind)
)

func init() {
	SchemeBuilder.Register(&CapacityClaim{}, &CapacityClaimList{})
}
