// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/fabioaraujopt/provider-coreweave/apis/cluster/objectstorage/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Deployment.
func (mg *Deployment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.GatewayIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.GatewayIdsRefs,
		Selector:      mg.Spec.ForProvider.GatewayIdsSelector,
		To: reference.To{
			List:    &GatewayList{},
			Managed: &Gateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GatewayIds")
	}
	mg.Spec.ForProvider.GatewayIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.GatewayIdsRefs = mrsp.ResolvedReferences

	if mg.Spec.ForProvider.Model != nil {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Model.Bucket),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Model.BucketRef,
			Selector:     mg.Spec.ForProvider.Model.BucketSelector,
			To: reference.To{
				List:    &v1alpha1.BucketList{},
				Managed: &v1alpha1.Bucket{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Model.Bucket")
		}
		mg.Spec.ForProvider.Model.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Model.BucketRef = rsp.ResolvedReference

	}
	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.GatewayIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.GatewayIdsRefs,
		Selector:      mg.Spec.InitProvider.GatewayIdsSelector,
		To: reference.To{
			List:    &GatewayList{},
			Managed: &Gateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GatewayIds")
	}
	mg.Spec.InitProvider.GatewayIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.GatewayIdsRefs = mrsp.ResolvedReferences

	if mg.Spec.InitProvider.Model != nil {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Model.Bucket),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Model.BucketRef,
			Selector:     mg.Spec.InitProvider.Model.BucketSelector,
			To: reference.To{
				List:    &v1alpha1.BucketList{},
				Managed: &v1alpha1.Bucket{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Model.Bucket")
		}
		mg.Spec.InitProvider.Model.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Model.BucketRef = rsp.ResolvedReference

	}

	return nil
}
