// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type AuthInitParameters struct {

	// (Attributes) Use CoreWeave IAM authentication. (see below for nested schema)
	Coreweave *CoreweaveInitParameters `json:"coreweave,omitempty" tf:"coreweave,omitempty"`

	// (Attributes) Use Weights & Biases authentication. (see below for nested schema)
	WeightsAndBiases *WeightsAndBiasesInitParameters `json:"weightsAndBiases,omitempty" tf:"weights_and_biases,omitempty"`
}

type AuthObservation struct {

	// (Attributes) Use CoreWeave IAM authentication. (see below for nested schema)
	Coreweave *CoreweaveParameters `json:"coreweave,omitempty" tf:"coreweave,omitempty"`

	// (Attributes) Use Weights & Biases authentication. (see below for nested schema)
	WeightsAndBiases *WeightsAndBiasesObservation `json:"weightsAndBiases,omitempty" tf:"weights_and_biases,omitempty"`
}

type AuthParameters struct {

	// (Attributes) Use CoreWeave IAM authentication. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Coreweave *CoreweaveParameters `json:"coreweave,omitempty" tf:"coreweave,omitempty"`

	// (Attributes) Use Weights & Biases authentication. (see below for nested schema)
	// +kubebuilder:validation:Optional
	WeightsAndBiases *WeightsAndBiasesParameters `json:"weightsAndBiases,omitempty" tf:"weights_and_biases,omitempty"`
}

type BodyBasedInitParameters struct {

	// known API type for routing. Must be one of: API_TYPE_OPENAI.
	// The well-known API type for routing. Must be one of: `API_TYPE_OPENAI`.
	APIType *string `json:"apiType,omitempty" tf:"api_type,omitempty"`
}

type BodyBasedObservation struct {

	// known API type for routing. Must be one of: API_TYPE_OPENAI.
	// The well-known API type for routing. Must be one of: `API_TYPE_OPENAI`.
	APIType *string `json:"apiType,omitempty" tf:"api_type,omitempty"`
}

type BodyBasedParameters struct {

	// known API type for routing. Must be one of: API_TYPE_OPENAI.
	// The well-known API type for routing. Must be one of: `API_TYPE_OPENAI`.
	// +kubebuilder:validation:Optional
	APIType *string `json:"apiType" tf:"api_type,omitempty"`
}

type CoreweaveInitParameters struct {
}

type CoreweaveObservation struct {
}

type CoreweaveParameters struct {
}

type EndpointConfigurationInitParameters struct {

	// (Set of String) Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// +listType=set
	AdditionalDNS []*string `json:"additionalDns,omitempty" tf:"additional_dns,omitempty"`

	// length prefix for a single address (e.g. 203.0.113.5/32).
	// Client source IP ranges permitted to reach the gateway, in CIDR notation (IPv4 or IPv6). Up to 50 entries; an empty list applies no source restriction. Use a full-length prefix for a single address (e.g. `203.0.113.5/32`).
	// +listType=set
	AllowedSourceIPRanges []*string `json:"allowedSourceIpRanges,omitempty" tf:"allowed_source_ip_ranges,omitempty"`

	// (String) How client traffic reaches the gateway. Must be one of: EDGE_PROXY_MODE_MANAGED (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or EDGE_PROXY_MODE_DIRECT (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently EDGE_PROXY_MODE_MANAGED) applies.
	// How client traffic reaches the gateway. Must be one of: `EDGE_PROXY_MODE_MANAGED` (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or `EDGE_PROXY_MODE_DIRECT` (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently `EDGE_PROXY_MODE_MANAGED`) applies.
	EdgeProxyMode *string `json:"edgeProxyMode,omitempty" tf:"edge_proxy_mode,omitempty"`
}

type EndpointConfigurationObservation struct {

	// (Set of String) Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// +listType=set
	AdditionalDNS []*string `json:"additionalDns,omitempty" tf:"additional_dns,omitempty"`

	// length prefix for a single address (e.g. 203.0.113.5/32).
	// Client source IP ranges permitted to reach the gateway, in CIDR notation (IPv4 or IPv6). Up to 50 entries; an empty list applies no source restriction. Use a full-length prefix for a single address (e.g. `203.0.113.5/32`).
	// +listType=set
	AllowedSourceIPRanges []*string `json:"allowedSourceIpRanges,omitempty" tf:"allowed_source_ip_ranges,omitempty"`

	// (String) How client traffic reaches the gateway. Must be one of: EDGE_PROXY_MODE_MANAGED (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or EDGE_PROXY_MODE_DIRECT (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently EDGE_PROXY_MODE_MANAGED) applies.
	// How client traffic reaches the gateway. Must be one of: `EDGE_PROXY_MODE_MANAGED` (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or `EDGE_PROXY_MODE_DIRECT` (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently `EDGE_PROXY_MODE_MANAGED`) applies.
	EdgeProxyMode *string `json:"edgeProxyMode,omitempty" tf:"edge_proxy_mode,omitempty"`
}

type EndpointConfigurationParameters struct {

	// (Set of String) Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// Additional DNS names for the gateway endpoint. These DNS names must be manually configured to point to the gateway endpoint.
	// +kubebuilder:validation:Optional
	// +listType=set
	AdditionalDNS []*string `json:"additionalDns,omitempty" tf:"additional_dns,omitempty"`

	// length prefix for a single address (e.g. 203.0.113.5/32).
	// Client source IP ranges permitted to reach the gateway, in CIDR notation (IPv4 or IPv6). Up to 50 entries; an empty list applies no source restriction. Use a full-length prefix for a single address (e.g. `203.0.113.5/32`).
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedSourceIPRanges []*string `json:"allowedSourceIpRanges,omitempty" tf:"allowed_source_ip_ranges,omitempty"`

	// (String) How client traffic reaches the gateway. Must be one of: EDGE_PROXY_MODE_MANAGED (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or EDGE_PROXY_MODE_DIRECT (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently EDGE_PROXY_MODE_MANAGED) applies.
	// How client traffic reaches the gateway. Must be one of: `EDGE_PROXY_MODE_MANAGED` (traffic is proxied through CoreWeave's managed edge network: DDoS mitigation and WAF, with TLS terminated at the edge and the origin address kept out of public DNS) or `EDGE_PROXY_MODE_DIRECT` (clients connect straight to the gateway's load balancer, with no edge filtering and the load balancer address published in DNS). When unset, the platform default (currently `EDGE_PROXY_MODE_MANAGED`) applies.
	// +kubebuilder:validation:Optional
	EdgeProxyMode *string `json:"edgeProxyMode,omitempty" tf:"edge_proxy_mode,omitempty"`
}

type GatewayConditionsInitParameters struct {
}

type GatewayConditionsObservation struct {

	// (String) RFC3339 timestamp of the last condition transition.
	// RFC3339 timestamp of the last condition transition.
	LastUpdateTime *string `json:"lastUpdateTime,omitempty" tf:"last_update_time,omitempty"`

	// readable message about the condition's last transition.
	// A human-readable message about the condition's last transition.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// readable reason for the condition's last transition.
	// A short, machine-readable reason for the condition's last transition.
	Reason *string `json:"reason,omitempty" tf:"reason,omitempty"`

	// (String) The current status of the gateway. See the Inference API overview for status values.
	// The condition status (`True`, `False`, or `Unknown`).
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The condition type (e.g. Ready, Progressing).
	// The condition type (e.g. `Ready`, `Progressing`).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type GatewayConditionsParameters struct {
}

type GatewayInitParameters struct {

	// (Attributes) The authentication configuration for the gateway. Exactly one of coreweave or weights_and_biases must be specified. (see below for nested schema)
	Auth *AuthInitParameters `json:"auth,omitempty" tf:"auth,omitempty"`

	// (Attributes) Additional endpoint configuration options. (see below for nested schema)
	EndpointConfiguration *EndpointConfigurationInitParameters `json:"endpointConfiguration,omitempty" tf:"endpoint_configuration,omitempty"`

	// readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	// The human-readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) The routing configuration for the gateway. Exactly one of body_based, header_based, or path_based must be specified. (see below for nested schema)
	Routing *RoutingInitParameters `json:"routing,omitempty" tf:"routing,omitempty"`

	// (Set of String) The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type GatewayObservation struct {

	// (Attributes) The authentication configuration for the gateway. Exactly one of coreweave or weights_and_biases must be specified. (see below for nested schema)
	Auth *AuthObservation `json:"auth,omitempty" tf:"auth,omitempty"`

	// (Attributes List) Detailed status conditions for the gateway. (see below for nested schema)
	Conditions []GatewayConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`

	// (String) RFC3339 timestamp of when the gateway was created.
	// RFC3339 timestamp of when the gateway was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes) Additional endpoint configuration options. (see below for nested schema)
	EndpointConfiguration *EndpointConfigurationObservation `json:"endpointConfiguration,omitempty" tf:"endpoint_configuration,omitempty"`

	// (Set of String) The endpoint URIs for the gateway.
	// The endpoint URIs for the gateway.
	// +listType=set
	Endpoints []*string `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// (String) The unique identifier of the gateway.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	// The human-readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The organization ID that owns the gateway.
	// The organization ID that owns the gateway.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (Attributes) The routing configuration for the gateway. Exactly one of body_based, header_based, or path_based must be specified. (see below for nested schema)
	Routing *RoutingObservation `json:"routing,omitempty" tf:"routing,omitempty"`

	// (String) The current status of the gateway. See the Inference API overview for status values.
	// The current status of the gateway. See the [Inference API overview](https://docs.coreweave.com/products/inference/reference/api-overview) for status values.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) RFC3339 timestamp of when the gateway was last updated.
	// RFC3339 timestamp of when the gateway was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Set of String) The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type GatewayParameters struct {

	// (Attributes) The authentication configuration for the gateway. Exactly one of coreweave or weights_and_biases must be specified. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Auth *AuthParameters `json:"auth,omitempty" tf:"auth,omitempty"`

	// (Attributes) Additional endpoint configuration options. (see below for nested schema)
	// +kubebuilder:validation:Optional
	EndpointConfiguration *EndpointConfigurationParameters `json:"endpointConfiguration,omitempty" tf:"endpoint_configuration,omitempty"`

	// readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	// The human-readable name of the gateway. Capped at 38 characters so the derived public FQDN fits within the 64-character X.509 Common Name limit.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) The routing configuration for the gateway. Exactly one of body_based, header_based, or path_based must be specified. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Routing *RoutingParameters `json:"routing,omitempty" tf:"routing,omitempty"`

	// (Set of String) The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// The zones to make the gateway available in. Limits where deployments associated with the gateway may exist.
	// +kubebuilder:validation:Optional
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type HeaderBasedInitParameters struct {

	// (String) The name of the header to use for routing.
	// The name of the header to use for routing.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`
}

type HeaderBasedObservation struct {

	// (String) The name of the header to use for routing.
	// The name of the header to use for routing.
	HeaderName *string `json:"headerName,omitempty" tf:"header_name,omitempty"`
}

type HeaderBasedParameters struct {

	// (String) The name of the header to use for routing.
	// The name of the header to use for routing.
	// +kubebuilder:validation:Optional
	HeaderName *string `json:"headerName" tf:"header_name,omitempty"`
}

type PathBasedInitParameters struct {
}

type PathBasedObservation struct {
}

type PathBasedParameters struct {
}

type RoutingInitParameters struct {

	// based routing configuration. Routes requests based on the request body content. (see below for nested schema)
	BodyBased *BodyBasedInitParameters `json:"bodyBased,omitempty" tf:"body_based,omitempty"`

	// based routing configuration. Routes requests using a header value to match the model by name. (see below for nested schema)
	HeaderBased *HeaderBasedInitParameters `json:"headerBased,omitempty" tf:"header_based,omitempty"`

	// based routing configuration. Routes requests based on the URL path. (see below for nested schema)
	PathBased *PathBasedInitParameters `json:"pathBased,omitempty" tf:"path_based,omitempty"`
}

type RoutingObservation struct {

	// based routing configuration. Routes requests based on the request body content. (see below for nested schema)
	BodyBased *BodyBasedObservation `json:"bodyBased,omitempty" tf:"body_based,omitempty"`

	// based routing configuration. Routes requests using a header value to match the model by name. (see below for nested schema)
	HeaderBased *HeaderBasedObservation `json:"headerBased,omitempty" tf:"header_based,omitempty"`

	// based routing configuration. Routes requests based on the URL path. (see below for nested schema)
	PathBased *PathBasedParameters `json:"pathBased,omitempty" tf:"path_based,omitempty"`
}

type RoutingParameters struct {

	// based routing configuration. Routes requests based on the request body content. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BodyBased *BodyBasedParameters `json:"bodyBased,omitempty" tf:"body_based,omitempty"`

	// based routing configuration. Routes requests using a header value to match the model by name. (see below for nested schema)
	// +kubebuilder:validation:Optional
	HeaderBased *HeaderBasedParameters `json:"headerBased,omitempty" tf:"header_based,omitempty"`

	// based routing configuration. Routes requests based on the URL path. (see below for nested schema)
	// +kubebuilder:validation:Optional
	PathBased *PathBasedParameters `json:"pathBased,omitempty" tf:"path_based,omitempty"`
}

type WeightsAndBiasesInitParameters struct {

	// (String, Sensitive) The organization API key for Weights & Biases. Requires server_url to also be set.
	// The organization API key for Weights & Biases. Requires `server_url` to also be set.
	APIKeySecretRef *v2.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (Boolean) Whether to enable Weights & Biases controlled rate limiting.
	// Whether to enable Weights & Biases controlled rate limiting.
	EnableRateLimiting *bool `json:"enableRateLimiting,omitempty" tf:"enable_rate_limiting,omitempty"`

	// (Boolean) Whether to send usage data to Weights & Biases.
	// Whether to send usage data to Weights & Biases.
	EnableUsageReports *bool `json:"enableUsageReports,omitempty" tf:"enable_usage_reports,omitempty"`

	// (String) The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	// The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

type WeightsAndBiasesObservation struct {

	// (Boolean) Whether to enable Weights & Biases controlled rate limiting.
	// Whether to enable Weights & Biases controlled rate limiting.
	EnableRateLimiting *bool `json:"enableRateLimiting,omitempty" tf:"enable_rate_limiting,omitempty"`

	// (Boolean) Whether to send usage data to Weights & Biases.
	// Whether to send usage data to Weights & Biases.
	EnableUsageReports *bool `json:"enableUsageReports,omitempty" tf:"enable_usage_reports,omitempty"`

	// (String) The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	// The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

type WeightsAndBiasesParameters struct {

	// (String, Sensitive) The organization API key for Weights & Biases. Requires server_url to also be set.
	// The organization API key for Weights & Biases. Requires `server_url` to also be set.
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v2.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (Boolean) Whether to enable Weights & Biases controlled rate limiting.
	// Whether to enable Weights & Biases controlled rate limiting.
	// +kubebuilder:validation:Optional
	EnableRateLimiting *bool `json:"enableRateLimiting,omitempty" tf:"enable_rate_limiting,omitempty"`

	// (Boolean) Whether to send usage data to Weights & Biases.
	// Whether to send usage data to Weights & Biases.
	// +kubebuilder:validation:Optional
	EnableUsageReports *bool `json:"enableUsageReports,omitempty" tf:"enable_usage_reports,omitempty"`

	// (String) The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	// The Weights & Biases server URL. Defaults to the shared SaaS instance if not set.
	// +kubebuilder:validation:Optional
	ServerURL *string `json:"serverUrl,omitempty" tf:"server_url,omitempty"`
}

// GatewaySpec defines the desired state of Gateway
type GatewaySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   GatewayParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GatewayInitParameters `json:"initProvider,omitempty"`
}

// GatewayStatus defines the observed state of Gateway.
type GatewayStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               GatewayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Gateway is the Schema for the Gateways API. Create and manage CoreWeave Managed Inference https://docs.coreweave.com/products/inference gateways. See gateways https://docs.coreweave.com/products/inference/gateways for authentication and routing details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,coreweave}
type Gateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.auth) || (has(self.initProvider) && has(self.initProvider.auth))",message="spec.forProvider.auth is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.routing) || (has(self.initProvider) && has(self.initProvider.routing))",message="spec.forProvider.routing is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zones) || (has(self.initProvider) && has(self.initProvider.zones))",message="spec.forProvider.zones is a required parameter"
	Spec   GatewaySpec   `json:"spec"`
	Status GatewayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayList contains a list of Gateways
type GatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Gateway `json:"items"`
}

// Repository type metadata.
var (
	Gateway_Kind             = "Gateway"
	Gateway_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Gateway_Kind}.String()
	Gateway_KindAPIVersion   = Gateway_Kind + "." + CRDGroupVersion.String()
	Gateway_GroupVersionKind = CRDGroupVersion.WithKind(Gateway_Kind)
)

func init() {
	SchemeBuilder.Register(&Gateway{}, &GatewayList{})
}
