apiVersion: workloadfederation.coreweave.m.crossplane.io/v1alpha1
kind: OIDCConfig
metadata:
  annotations:
    meta.upbound.io/example-id: workloadfederation/v1alpha1/oidcconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    audience: https://coreweave.com/iam
    description: HCP Terraform workload identity
    issuerUrl: https://app.terraform.io
    name: hcp-terraform
